### ISSUE TITLE
Lizenz: Non Commercial und Open Source

### ISSUE THREAD

**Issue by davidmehren** [foss-ag/orga_guidelines#10]
Mir ist gerade aufgefallen, dass der Non-Commercial Teil der CC-Lizenz die wir aktuell nutzen dem Open Source Gedanken widerspricht. Deshalb wird die NC-Lizenz auch von folgenden Stellen nicht empfohlen:
- https://choosealicense.com/non-software/
- https://www.oshwa.org/2014/05/21/cc-oshw/

Auch https://creativecommons.org/licenses/?lang=de nennt die BY-SA Lizenz als Entsprechung für „normale“ Open Source Lizenzen.

Ich schlage daher vor, die Lizenz auf CC-BY-SA 4.0 zu ändern. Hat den netten Vorteil, dass GitHub sie kennt und oben im Repo anzeigt (https://help.github.com/articles/licensing-a-repository/)

**Comment by Eisfunke** [comment]
Die Non-Commercial-Lizenzen sind keine freien Lizenzen, das stimmt.

Hierbei geht es jetzt aber ja auch nicht um ein Projekt, das wir öffentlich machen wollen, sondern um AG-interne Richtlinien, da halte ich das auch nicht für erforderlich.

Da mir jetzt aber auch keine Möglichkeit einfällt, wie man diese Guidelines kommerziell nutzen könnte, und ich auch nicht wüsste, warum uns das stören sollte, können wir die Lizenz auch gerne ändern. Share-Alike können wir von mir aus dann auch gleich rausnehmen.

Abgesehen davon halte ich es sowieso für unnötig, das hier zu lizensieren, da es sich ja nicht um ein Werk/Produkt handelt, das von Menschen genutzt werden soll, sondern, wie gesagt, schlicht um AG-interne Richtlinien für uns selber.

**Comment by Lazalatin** [comment]
Ich unterstütze die von @Eisfunke vorgebrachten Argumente. Meines Erachtens wäre eine restriktive Lizenz oder gar keine die bessere Lösung gewesen!
Daher ist es auch okay, dass dieses Repo keine sog. Free-Culture Lizenz hat.  
  
Ich werde daher dieses Issue heute Nacht mit `invalid` schließen, sofern nichts Weiteres vorgebracht wird.
