### ISSUE TITLE
Version 2 erstellen

### ISSUE THREAD

**Issue by Lazalatin** [foss-ag/orga_guidelines#12]
Hallo zusammen,

dieses Issue wird am Mittwoch, den 29.11.2017 ggn. 20 Uhr geschlossen und Version 2 der Guidelines released. Mit dem Release werden die Guidelines auf das GitHub und neue Kanäle angewandt.

Bis zu diesem Zeitpunkt können noch Issues eröffnet und diskutiert werden, die nachfolgenden generieren Version 3.

**Comment by dragetd** [comment]
Ich erinnere mich dunkel an noch 1-2 Punkte die letzten Donnerstag erwähnt wurden, die wir hier noch nicht diskutiert haben. Leider erinnere ich mich nicht genau, was er war. :( Aber das soll uns ja nicht hindern mal den v2 Tag zu setzen. :-)

**Comment by Lazalatin** [comment]
Dieser Release ist umgesetzt. Siehe Tag v2
