### ISSUE TITLE
Creation of a seperate file concerning the "sponsoring guidelines"

### ISSUE THREAD

**Issue by lxndio** [foss-ag/orga_guidelines#13]
As discussed at the FOSS-AG meeting on 2017-11-30, it may be required to create a seperate guideline file regarding the general opinion on sponsoring of AG projects or the AG itself by, possibly non-FOSS, companies.

Issues Deutsch oder Englisch? Hmm, hier noch mal auf Deutsch:

Wie wir bereits bei der Sitzung am 30.11.2017 diskutiert haben, wäre es möglicherweise vonnöten, eine weitere Datei anzulegen und somit Guidelines für das Sponsoring von AG Projekten oder der AG selber aufzustellen.

**Comment by Lazalatin** [comment]
Because this repo only concerns people from germany (because it is solely for our AG structure) I prefered writing my comments in german, but it does not really matter :laughing: 

------
Ich schreibe auf Deutsch, weil ich nicht sehe dass es nicht des Deutschen mächtige Menschen interessiert, aber im Grunde ist es gleichgültig.

Ich befürworte diesen Vorschlag. Falls du möchtest kannst du an einem PR arbeiten, oder aber Meinungen Dritter abwarten :+1:

**Comment by dragetd** [comment]
Schreibt ruhig auf deutsch… wir erwarten hier nicht internationale Beteiligung. xD

IMHO waren wir uns alle eigentlich bis jetzt immer einig darüber, dass "Sponsoring" nur OK ist, wenn es keine Firma bewirbt oder an eine API/Technologie bindet. Aber ansonsten hat uns ja auch der Alumni gesponsert, und das ist ja auch gut so.

Ich wäre nicht dafür, das noch extra nieder zu schreiben, vor allem solange es keinen echten Diskurs darüber gab.

**Comment by Eisfunke** [comment]
Also erstmal finde ich nicht, dass wir dafür eine eigene Datei bräuchten. *Wenn* wir da was schriftlich festelegen wollen, dann sollte ein kurzer Absatz in der allgemeinen Datei vollkommen reichen.

Zur Frage selber bin ich dagegen, irgendwie für irgendeine Firma allgemein Werbung zu machen, ich bin vor allem auch dagegen, Geld anzunehmen oder so etwas. Etwas wie Sticker, die wir dann auch weitergeben, sind okay.

Aber wenn eine Firma was fossiges hat, das uns gefällt, und das vielleicht irgendwie in Kooperation mit uns vorstellen möchte, fände ich das absolut okay. Sollte dann aber auch eine Einzelfallentscheidung mit gesundem Menschenverstand bleiben.

Deswegen bin ich dafür, einfach nur so etwas wie "Wir machen keine Werbung für Unternehmen und nehmen keine Geschenke an." in die Guidelines zu übernehmen. Dafür hätte ich aber gerne noch ein Meinungsbild in einer Sitzung/Gruppe, bevor wir das tun.

**Comment by dragetd** [comment]
Ich denke, das bekommen wir online geklärt. :)

Was ist mit Unternehmen, die im Open-Source Bereich tätig sind? Canonical? OpenSuse? ThomasKrenn? Ich würde auch gerne weiterhin Unternehmen z.B. auf Twitter 'loben', die sich besonders aktiv im FOSS-Bereich zeigen.

Deswegen denke ich ist so etwas case-by-case einfacher. Ich sehe keine Gefahr, dass wir ein Amazon-Alexa-Hackathon machen werden. ;-)

Wir sollten uns auch davor hüten, nicht zu viel auf zu schreiben, speziell solange es funktioniert.

**Comment by Scosh** [comment]
Stimme @Eisfunke hier wieder zu. Eine extra Datei ist glaube ich overkill, aber ein kurzer Satz in der allgemeinen Datei, der unseren Standpunkt dazu mal für neue und Außenstehende und auch uns in Zukunft klar macht, wäre sehr gut. ^^

**Comment by dragetd** [comment]
Wie soll der Satz denn aussehen? Nicht so einfach den geschickt zu formulieren.

'Wir nehmen kein Sponsoring von Firmen für Events an, wenn dieses an Werbe-Bedienungen geknüpft ist oder die Firma nicht deutlich FOSS-Affin ist.'

Oh man xD

**Comment by Lazalatin** [comment]
Auch hier empfehle ich wieder die positive Formulierungsweise:
'Wir freuen uns über Sponsorings für unsere Events seitens Firmen, welche sich durch Engangement im OpenSource-Bereich verdient gemacht haben.'

Was haltet ihr davon?

**Comment by dragetd** [comment]
Das klingt irgendwie nicht mehr nach dem Aufmacher von 'Wir mögen Sponsoring (meistens) nicht'. :-P

Was haltet ihr von dem Vorschlag, dass Case-By-Case zu entscheiden?

**Comment by ROYALBEFF** [comment]
Case-by-Case ist wahrscheinlich noch am sinnvollsten, wobei ich persönlich einem Sponsoring auch eher kritisch gegenüber stehe. Ich halte es für wichtiger, dass wir an unseren Prinzipien festhalten, als dass wir uns verkaufen. Ich würde z.B. auch nur dann Sticker eines Produkts in unsere Stickerbox aufnehmen, wenn wir das selber für ein gutes Produkt erachten und nicht, weil uns jemand Geld zugesteckt hat. Der Alumni stellt eine Ausnahme da, da er nicht daran interessiert ist ein Produkt/Service zu vermarkten, sondern seine Hauptaufgabe darin besteht, die Studenten (auch finanziell) zu unterstützen.

**Comment by lxndio** [comment]
Wie wäre es mit:

"Wir freuen uns über Sponsorings für unsere Events seitens Unternehmen, welche sich durch Engangement im OpenSource-Bereich verdient gemacht haben, weisen aber darauf hin, dass wir produktbasierte Spenden nicht annehmen und unsere Meinung oder Ausrichtung nicht käuflich ist."

Oder so ähnlich.

**Comment by Lazalatin** [comment]
Ist mir ein wenig zu dick aufgetragen ehrlich gesagt.

**Comment by dragetd** [comment]
Ich denke, dass wir uns alle einig sind, dass wir die Prinzipien von FOSS nicht 'verraten' wollen und so etwas wie den Alumni-Hackathon mit exklusiver Amazon-Bindung nicht machen wollen.

Gleichzeitig wäre aber auch 100%-kein-Sponsoring heuchlerisch und falsch, weil der Alumni uns bereits gesponsort hat, wir Sticker von der FSFE oder TOR haben und wir Webung für Distros von Firmen machen.

Ich würde folgenden Vorschlag machen:
Die Guidelines sind mehr dazu da, Verantwortlichkeiten zu klären. Was unsere 'Meinung' zu Firmen/Sponsoring ist, passt da nicht wirklcih rein.
Die Prinzipien und Ziele für die wir stehen, sind etwas anderes. Auch wenn ich den Wunsch verstehe, diese nieder zu schreiben, wäre ich immer noch dagegen, dass in die 'Guidelines' zu tun.

-> Stattdessen schlage ich vor, dass solche Dinge weiter unter 'Ziele der AG' formuliert werden und auf die Webseite kommen. Ein Text dazu steht bereits im Wiki (diesen bitte nicht ohne Nachfrage inhaltlich ändern).
Wir könnten eine Datei 'foss-ag-ambition.md' ins Repo https://github.com/foss-ag/website_foss-ag schmeißen mit dem jetzigen Text, in einem Issue weiter darüber diskutieren und es dann online stellen, wenn die Webseite steht.

**Comment by ROYALBEFF** [comment]
Allerdings haben wir da "Werbung" gemacht, weil wir die Projekte persönlich für wichtig halten und nicht weil wir Geld bekommen haben. Das ist nochmal was ganz anderes. Und Sponsoring seitens Alumni ist z.B. völlig ok.

**Comment by Scosh** [comment]
> Wir könnten eine Datei 'foss-ag-ambition.md' ins Repo https://github.com/foss-ag/website_foss-ag schmeißen mit dem jetzigen Text, in einem Issue weiter darüber diskutieren und es dann online stellen, wenn die Webseite steht.

Ist das für alle hier okay, wenn ich ein neues Issue dort aufmache, um die Diskussion weiterzuführen? Oder gibt es noch Gegenmeinungen zu diesem Vorschlag von @dragetd? :)

**Comment by dragetd** [comment]
Nope! Lasst uns bei dem Webseiten-Repo weiter diskutieren! :)

**Comment by Scosh** [comment]
[Neues Issue erstellt auf `website_foss-ag`](https://github.com/foss-ag/website_foss-ag/issues/1) 👈 👀
