### ISSUE TITLE
Gitea Nutzung für nicht-aktive

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#15]
Hallo zusammen,

es ist mir auch aufgefallen, dass es eigentlich dämlich ist, wenn Leute das Gitea nicht nutzen können für private Projekte. Finde ich nicht unbedingt sehr FOSSig so zu denken. o.o

Da der Server ja bei der Fachschaft steht und nicht mehr auf meinen Namen läuft, ist das rechtlich auch viel entspannter. Mein Vorschlag wäre also: Gitea offen für jeden der min. einmal bei einer Sitzung war? :)

**Comment by Lazalatin** [comment]
Wie wäre es mit "Jede Person, die anfragt"?

**Comment by davidmehren** [comment]
Ist mir im Prinzip egal (ich brauchs nicht und muss es nicht verwalten 😊), trotzdem ein paar Gedanken:

> Da der Server ja bei der Fachschaft steht und nicht mehr auf meinen Namen läuft, ist das rechtlich auch viel entspannter.

Naja, verantwortlich sind trotzdem: der Domaininhaber, der der im Impressum steht, die Serveradmins. Also dreimal nicht die Fachschaft 😇 

Keine Ahnung ob sich sowas lohnen würde, gibts nicht schon drölfzig Dienste die private Repos anbieten? Inklusive Fachschaft (aktuell Redmine, demnächst™ Gitea), GitHub, Bitbucket usw.

Zuletzt: Sind Repos mit privatem, proprietärem Code nicht das genaue Gegenteil von dem, was die FOSS-AG erreichen möchte?

**Comment by dragetd** [comment]
Ja, das war definitiv sehr doof ausgedrückt von mir im ersten Post! Natürlich sind wir weiter verantwortlich! Es war mehr so der Gedanke, dass NetCup mir nicht gleich alle meine Server abklemmt weil einmal was schief läuft. Da ist ein gewisser Puffer für Schindluder den auch Firmen treiben können.

Letztendlich entzieht uns das aber keiner Verantwortung darauf zu achten, das ist mir klar! :)

Und ob sich das 'lohnt' ist eine andere Frage. Nur wenn wir als AG so einen Dienst haben könnten wir ihn auch allen anbieten. Ich habe natürlich auch nichts dagegen bei dem bestehenden Vorgehen zu bleiben - wollte aber mal ein paar andere Meinungen!

**Comment by lxndio** [comment]
Ich würde den Dienst vielleicht nicht für "Außenstehende" anbieten; aber auf jeden Fall, für jeden innerhalb der AG, der lieb fragt.

In meinen Augen wäre eine sinnvolle Regelung, Zugriff nur persönlich zu erteilen. Es muss also jeder, der den Dienst nutzen möchte, vor/während/nach einer Sitzung einen Verantwortlichen bitten, ein Konto für ihn anzulegen.
So könnte man zumindest sicherstellen, dass man die Leute kennt, denen man Zugriff auf Gitea anvertraut und man kann ihnen im Zweifel (Stichwort Verantwortlichkeit) höchstpersönlich in den A**** treten, wenn sie den Dienst für was auch immer missbrauchen.

**Comment by Eisfunke** [comment]
Ich bin sowieso allgemein dafür, den Begriff "aktive Person" situationsabhängig und wenig streng auszulegen. Den wichtigsten Part daran finde ich einfach nur, dass bei sowas dann nachgefragt wird.

Im Fall von Gitea sehe ich aber auch kein Problem, das ganz zu öffnen, an jeden, der fragt.
Ist ja auch egal, ob sich das "lohnt". Es anzubieten schadet ja nichts, und ist die " fossigere" Alternative.

**Comment by Scosh** [comment]
Ich stimme auch @lxndio und @Eisfunke hier zu:

Zugriff zum Gitea sollte offen auf Nachfrage erteilt werden können. Es sollte aber quasi einen *Konsens* zwischen beiden Parteien geben, wo sowohl offen gefragt werden kann: "Hey, möchtest Du aktives Mitglied sein und Gitea Zugriff bekommen?" aber auch von der anderen Seite: "Hey, darf ich als 'aktiv' *offiziell* zählen und Gitea Zugriff bekommen?"

Kann man das irgendwie gut in den Guidelines verschriftlichen?

Es steht ja so *fast* schon da, mit "Member kriegen Zugriff auf FOSS-AG Dienste." Nur für mich fehlt die Aufklärung, dass jeder immer fragen kann.

**Comment by Lazalatin** [comment]
> Zugriff zum Gitea sollte offen auf Nachfrage erteilt werden können. Es sollte aber quasi einen Konsens zwischen beiden Parteien geben, wo sowohl offen gefragt werden kann: "Hey, möchtest Du aktives Mitglied sein und Gitea Zugriff bekommen?" aber auch von der anderen Seite: "Hey, darf ich als 'aktiv' offiziell zählen und Gitea Zugriff bekommen?"

Jain, ich bin hart dagegen hier den Begriff von aktiver Beteiligung und einem Zugriff auf unser Gitea zu vermischen. Ganz nach @Eisfunke würde ich es so auslegen, dass wir grundsätzlich alles zulassen, wenn es darüber einen Konsens gibt und niemand Bauchschmerzen damit hat. Das betrifft hier konkret Dinge wie den Gitea Zugriff.
Aktives Mitglied zu sein und mit mehr Rechten in unseren Repos, Member der GH Orga, usw. sollte getrennt betrachtet werden.

**Comment by dragetd** [comment]
Jo OK. Ich mache mal ein PR für den Text und versuche das was ihr gesagt habt, umzusetzen. Schaut mal, ob das so OK ist. :)
