### ISSUE TITLE
GitHub Teams sollten auch nicht-Member einladen können

### ISSUE THREAD

**Issue by Scosh** [foss-ag/orga_guidelines#17]
Okay … **das hier** war das konkrete Problem, welches ich mit den aktuellen Regelungen habe und am Donnerstag in der Sitzung äußerte.

Es muss sich wirklich nur eine Sache ändern, finde ich … nämlich, das Maintainer von GitHub Teams auch GitHub Nutzer einladen können, die eben *nicht* in unserer FOSS-AG Organisation sind.

Das würde auch nichts an unserer "Qualitätskontrolle" / "Ist das FOSS-AG relevant und approved?" Frage kaputt machen. Es muss ja noch immer ein GitHub-Organisationsmitglied *das Team erstellen.* Das Recht, Repos und Teams im Namen der FOSS-AG zu erstellen, sollte nach wie vor bei **aktiven Mitgliedern** bleiben.

Was aber meiner Meinung nach auf jeden Fall für die produktive Nutzung unserer Präsens auf GitHub geändert werden sollte, ist, wie oben gesagt, dass sobald ein Team von einem Mitglied erstellt ist, dieses Mitglied auch eben Menschen einladen kann, **die nicht in der GitHub-Organisation sind.**

Das ist wichtig, weil die GitHub Teams Funktion sonst nur sehr eingeschränkt von uns nützlich verwendet wird.

Es gibt halt Projekte, wo es Sinn ergibt, mehr Rechte auf einmal, auf mehrere Menschen zu erteilen, als nur PRs. Und das auch gleichzeitig über mehr als ein Repo. Für solche Fälle ist es nicht sinnvoll, GitHub-Team-Mitglieder meiner Meinung nach ar­bi­t­rär auf GitHub-Organisations-Member zu beschränken.

Diese Möglichkeit sollte Maintainern offen bleiben.

**Comment by davidmehren** [comment]
Leider können nur Mitglieder der Organisation Teams hinzugefügt werden: https://help.github.com/articles/about-teams/

**Comment by Lazalatin** [comment]
> Es muss sich wirklich nur eine Sache ändern, finde ich … nämlich, das Maintainer von GitHub Teams auch GitHub Nutzer einladen können, die eben nicht in unserer FOSS-AG Organisation sind.

Ja, dass dies nicht feingranularer einstellbar ist, ist wirklich eine Schande. Aber leider ist das nicht anders bei GH vorgesehen. Warum ich dies auch nicht für notwendig/richtig erachte werde ich später ausführen.

> Was aber meiner Meinung nach auf jeden Fall für die produktive Nutzung unserer Präsens auf GitHub geändert werden sollte, ist, wie oben gesagt, dass sobald ein Team von einem Mitglied erstellt ist, dieses Mitglied auch eben Menschen einladen kann, die nicht in der GitHub-Organisation sind.

Das scheint mir im leichten Widerspruch zu oben zu sein, denn Maintainer sind ja die Team-Member, welche Orgamember einladen können, aber ich akzeptiere das mal so.
Neben der Tatsache dass dies bei GitHub technisch nicht möglich ist, ist es auch so, dass es gewünscht ist, dass nicht-Member nicht in Teams kommen können.

> Das ist wichtig, weil die GitHub Teams Funktion sonst nur sehr eingeschränkt von uns nützlich verwendet wird.

Wie Michael bereits sagte, ist dies nicht so ganz richtig, denn üblicherweise sollte ein Team bzw. Projekt nur wenige Repos haben. Werden es viele ist das ein krass seltener Usecase oder man macht was falsch.

> Es gibt halt Projekte, wo es Sinn ergibt, mehr Rechte auf einmal, auf mehrere Menschen zu erteilen, als nur PRs.

Ja, die mag es geben, aber diese sind selten. Man geht Risiken ein wenn man mehr Rechte verteilt als notwendig. Auch wenn Menschen gerne so arrogant sind zu denken: "Ich brauche keine PRs weil ich mit write-Rechten schon nichts falsch committe." Das ist leider nicht korrekt, ich denke daran wie oft ich schon commits falsch gesetzt habe und wenn diese in einem nicht geschützten master-branch landen ist das Geheule schnell groß.

> Und das auch gleichzeitig über mehr als ein Repo. Für solche Fälle ist es nicht sinnvoll, GitHub-Team-Mitglieder meiner Meinung nach ar­bi­t­rär auf GitHub-Organisations-Member zu beschränken.

Über mehr als ein Repo Rechte einzustellen ist mit Teams möglich, Contributer von außen müssen separiert mit Rechten versehen werden, dies ist aber ohne Weiteres machbar und ein geringer Overhead. Auch hier wieder: Es ist technisch nicht möglich Team Member von Orga Member getrennt zu verwalten.

------
Ich erlaube mir noch ein Schlußwort:
Es ist unstrittig, dass auch Menschen, welche nicht aktive Mitglieder der AG sind befähigt sein sollten, an Projekten teilzuhaben und zu ihnen beizutragen. Dazu ist GitHub eine geeignete Plattform.
Es ist strittig, ob diese Menschen Teil eines Teams und damit gleichzeitig Teil der Orga sein sollten. Dazu kommt von mir ein klares **Nein**. Nicht-Aktive werden, sobald sie sich beteiligen und contributen auch irgendwann zu Aktiven und damit automatisch Teile der Teams an deren Projekten sie sich bisher beteiligten. Daher ist die Zahl an externen Contributern wohl dauerhaft überschaubar.
Ich denke also es ist für die Verwaltung der Sache am Besten zu akzeptieren, dass GH nicht die Möglichkeit bietet, die Semantik eines Teams im Sinne der FOSS-AG abzubilden und nach dem least-neccessary-rights Prinzip vorzugehen. Dabei soll den Teams allerdings nach wie vor freigestellt sein, was sie als nötiges Mindestrechtelevel betrachten.

**Comment by Scosh** [comment]
Jo … ich find es nach wie vor schade, dass es rein technisch auf GitHub nicht möglich ist :( aber ich verstehe die philosophische Begründung auch, weshalb man dagegen ist.

> Es ist strittig, ob diese Menschen Teil eines Teams und damit gleichzeitig Teil der Orga sein sollten. Dazu kommt von mir ein klares Nein.

Ja, du hast Recht, ich bin auch dagegen, Menschen sinnfrei in die Orga zu stecken. 

---

Mein Anliegen ist daraus entstanden, dass es für `unwort` eher schwieriger innerhalb der FOSS-AG Organisation auf GitHub war, das Projekt ordentlich (oder, so wie wir das vielleicht wollten) zu verwalten, weil eben die meisten Interessierten nicht in der Orga sind.

Vielleicht ist das aber eher ein Indiz für ein bereits funktionierendes System, das zeigt, dass `unwort` nicht direkt genug mit der FOSS-AG zu tun hat, um so sinnvoll gesteuert zu werden, sollte das Projekt tatsächlich jemals etwas größer werden oder so … Aber die Freiheit besteht ja von unserer Seite, das auf GitHub umzulegen und die FOSS-AG trotzdem als Rahmen für die Entwicklung etc. zu benutzen.

Deshalb war es wohl eher ein Missverständnis meinerseits (wie @Lazalatin vielleicht doch richtig in der Sitzung meinte, auch wenn hart :P) über die Zielsetzung und Funktion unserer GitHub-Organisation.

Ich bin also dafür das Issue zu schließen, von meiner Seite aus hat es sich zumindest erübrigt.
