### ISSUE TITLE
Diskussion - GitHub Owner

### ISSUE THREAD

**Issue by Lazalatin** [foss-ag/orga_guidelines#2]
> - Struktur für GitHub (Draft):
>   - Siehe auch [Guidlines FOSS-AG](guidlines_foss-ag.md).
>   - *Alternative 1*: Es gibt einen Owner-Account der keine natürlichen Person direkt zugeordnet ist. 3 Personen die darauf Zugriff haben (oder mit geteilter 2FA).
>   - *Alternative 2*: Es gib 3 Owner.
>     - Owner halten sich an die Konventionen der Teams (z.B. Commits per PR)

Ich persönlich würde die Variante mit 3 natürlichen Accounts als Owner der Orga bevorzugen.
Als ursprüngliche Personen für diese Rollen schlage ich @dragetd @ThiefOfTime und @Lazalatin vor. Über spätere Änderungen dieser Rollenzuweisungen sollte auch mal gesprochen werden, aber nicht unbedingt zu diesem Zeitpunkt.

So far
~laz

**Comment by davidmehren** [comment]
Ich bevorzuge `Alternative 1`, damit man nicht versehentlich direkt in ein Repo pushen kann, für das man eigentlich nur PR-Zugriff hätte.

**Comment by Eisfunke** [comment]
Ich wäre für Alternative 2 mit drei normalen Ownern. GitHub-Accounts sind ja nun nicht dafür gedacht, geteilt zu werden. Dann mit 2FA aufteilen hört sich für meinen Geschmack irgendwie zu hacky an.

Das aber unter der Voraussetzung, dass die vorgeschlagenen Owner (den Vorschlag von @Lazalatin finde ich gut) meinen, dass das mit dem versehentlichen Pushen hinzubekommen, ansonsten wäre ein Extra-Owner-Account wohl doch die bessere Wahl.

**Comment by InnayTool** [comment]
Ich finde einen eigenen Account irgendwie auch nich so toll, weil das ja eigentlich so nich vorgesehen ist.
Und ich habe bis jz noch nichts ausversehen commited. Keine Ahnung, ob das vorkommt.

**Comment by davidmehren** [comment]
Owner haben halt Schreibrechte auf allen Repos. Vergisst man also bei einem Repo von jemand anderem auf "Fork" zu klicken und pusht dann, macht Github das kommentarlos. So kann man versehentlich anderer Leute Dinge ohne PR zerschießen. Das vermeidet der Orga-Account.

**Comment by InnayTool** [comment]
ja is mir schon klar, ich weiß es nich, ob das passiert

**Comment by Lazalatin** [comment]
> Owner haben halt Schreibrechte auf allen Repos. Vergisst man also bei einem Repo von jemand anderem auf "Fork" zu klicken und pusht dann, macht Github das kommentarlos. So kann man versehentlich anderer Leute Dinge ohne PR zerschießen. Das vermeidet der Orga-Account.

Ich gebe hierbei zu bedenken, dass dies durch die Verwendung eines Orga-Accounts zwar direkt verhindert wird, aber bei eventuellen Geschehnissen die Nicht-Abstreitbarkeit der Aktionen nicht gewährleistet ist. Bei personengebundenen Accounts ist die Zuständigkeit eindeutig.

Ich weise für folgende Kommentare darauf hin, dass hier auch erarbeitet werden soll, welches dieser Modelle wir kommende Woche umsetzen werden. Rege Beteiligung ist also gewünscht, da ich ungern auf dem wackeligen Fundament von 4 Meinungsäußerungen stehen mag.

**Comment by dragetd** [comment]
Ich denke net. Und wenn ja, bekommt David jedes mal eine mate von mir ausgegeben! Ich mach gleich mal einen PR :)
