### ISSUE TITLE
v3 Release

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#21]
Gibt es noch irgendwo Bedenken? Bitte äußern! Ich würde gerne vor nächster Sitzung dann einmal das v3 Release schnüren. :)

**Comment by Lazalatin** [comment]
Äh ist denn inhaltlich was interessantes passiert?

**Comment by ROYALBEFF** [comment]
Von dem was ich so sehe nicht wirklich. Von mir aus kann v3 released werden.

**Comment by Lazalatin** [comment]
Dann sehe ich nicht den Grund für ein v3 aber gut... v2.1 wäre angemessener...

**Comment by dragetd** [comment]
v3 oder von mir aus v2017-12-11
Aber wir fangen jetzt nicht mit Sub-Versionsnummern an. :-P

**Comment by Lazalatin** [comment]
Minor version!!! :-O

**Comment by InnayTool** [comment]
Fahrradschuppen!

**Comment by dragetd** [comment]
@Lazalatin Wenn, dann SemVer (https://semver.org/). Sprich v2.0.1. Aber das ist für Software. Wir schreiben ein Dokument. Da wäre höchstens ein 'Stand' sinnvoll mit Datum (also v2017-12-10).

Aber 2.1 fände ich echt doof. :(

**Comment by Lazalatin** [comment]
Du hast Recht bzgl semver.

Also gut. Dann vllt Datum statt Versionen?

**Comment by dragetd** [comment]
Okay, machen wir Datum! :)
