### ISSUE TITLE
Guidelines für AG Treffen.

### ISSUE THREAD

**Issue by fes0j** [foss-ag/orga_guidelines#22]
Mit zunehmender Beteiligung haben wir auch unsere Treffen immer mehr strukturiert.

Vielleicht ist es sinnvoll Ideen aus der [Sitzung Nr. 72](https://fsinfo.cs.tu-dortmund.de/ags/foss-ag/protokoll#sitzung_nr_72) und aktuelle Abläufe aufzuschreiben.

Bisher wurde in Organisations- (orga) und Stammtischthemen unterschieden. Zusätzlich wollen wir eine Phase für "Hackgruppen" (oder ein anderer Name?) einführen, in der dann spezielle Diskussionen oder konkrete Arbeit und Absprache für laufende Projekte stattfinden.

**Comment by dragetd** [comment]
Erster Text ist im #23. Please comment. :)

**Comment by dragetd** [comment]
Die erste Version ist gemerged. Dies ist noch nicht endgültig.

Aber für Anliegen mit dem aktuellen Text bitte einzelne Issues erstellen die sich jeweils um ein Thema drehen, danke.
