### ISSUE TITLE
Dokumentation "Handzeichen"

### ISSUE THREAD

**Issue by Scosh** [foss-ag/orga_guidelines#26]
In der Datei [meetings.md](https://github.com/foss-ag/orga_guidelines/blob/master/doc/meetings.md) wird die Benutzung von Handzeichen bei größeren Gruppen erwähnt:

> Bei größeren Runden: Handzeichen nutzen!

Möchten wir die Handzeichen, die wir bei Treffen verwenden mal offiziel irgendwo (z.B. direkt in diesem Repo) festhalten?

Wir benutzen ja ein paar 'akzeptierte Standardzeichen,' die andere Gruppen auch nutzen . Aber mittlerweile haben wir ja zusätzlich einige eigene. :3 

Ich würde mich auch erklären, hierfür, zusammen mit dem @foss-ag/graphics team, ein paar Zeichnungen oder gar Animationen anzufertigen — wenn wir wirklich so fancy sein möchten.

Einfachere Lösungen, wie Zeichnungen oder Fotos für die Handzeichen von "lizenzfreien" Bildquellen zu organisieren, sind aber natürlich auch okay. Vielleicht auch erst einmal besser, damit wir schonmal etwas dafür dokumentiert haben.

**Comment by dragetd** [comment]
IMHO haben wir schon (schmerzlich) viel 'dokumentiert'. Ich wäre dagegen, das jetzt auch noch aufzuschreiben. Wie man sich 'meldet' sollte auch jeder Gast so wissen. Darüber hinaus sind das so Dinge die man spontan klären kann.

Finde das ist nicht unbedingt relevant für das Dokument.

**Comment by davidmehren** [comment]
Man könnte diesen Link einbauen: https://kif.fsinf.de/wiki/Erst-Kiffel#Handzeichen

**Comment by davidmehren** [comment]
Man könnte diesen Link einbauen: https://kif.fsinf.de/wiki/Erst-Kiffel#Handzeichen

**Comment by davidmehren** [comment]
Und wo wir bei Diskussionen sind: Die KIF hat "Direkt Dazu" a~~n~~**b**geschafft. Finde darüber könnten wir auch nachdenken. Begründung dazu (sowie viele weitere Hinweise zum Führen einer geordneten Diskussion) unter https://kif.fsinf.de/wiki/KIF370:Diskussionskultur#Resolution

**Comment by Scosh** [comment]
Also ich kann @dragetd verstehen, dass das möglicherweise zu viel Doku ist "an der falschen Stelle."

Ich denke es wäre aber gerade für neue Mitglieder praktisch, eine Übersicht zu haben. — Um eben nicht so verwirrt zu sein, warum alle Leute so komische Dinge mit ihren Händen tun. Ich kannte diese Handzeichen vor der FOSS-AG z.B. auch noch nicht … 

Man kommt aber andererseits mit den Zeichen ziemlich schnell rein, wenn jemand es einem kurz zeigt und erklärt. Also ist jetzt die Frage, wie wichtig das wirklich ist.

Ich fände aber @davidmehren's Vorschlag, den Link vielleicht direkt in die `meetings.md` Datei einzubauen, doch erstmal ganz gut. Das könnte z.B. so aussehen:

> Bei größeren Runden: [Handzeichen](https://kif.fsinf.de/wiki/Erst-Kiffel#Handzeichen) nutzen!

Was haltet ihr davon?

---

Zu Davids zweitem Punkt:

> Und wo wir bei Diskussionen sind: Die KIF hat "Direkt Dazu" angeschafft. 

Du meintest glaube ich *abgeschafft, oder? :P 

Weil ja, vielleicht ist die Diskussion in diesem Portal gerade nicht angebracht (oder vielleicht gerade doch?), aber ich finde es ist der Rede wert.

Ich habe letztes mal auch dieses Handzeichen ausgenutzt. Und da wir ja immer versuchen, den Redefluss in unseren Sitzungen zu verbessern, müsste man eventuell darüber sprechen, welche Handzeichen positiv dazu beitragen und welche nicht.

**Comment by davidmehren** [comment]
> Du meintest glaube ich *abgeschafft, oder? :P

Jo :D

> Ich habe letztes mal auch dieses Handzeichen ausgenutzt. Und da wir ja immer versuchen, den Redefluss in unseren Sitzungen zu verbessern, müsste man eventuell darüber sprechen, welche Handzeichen positiv dazu beitragen und welche nicht.

Ich fänd das einen interessanten Diskussionspunkt. Vielleicht müssen wir uns da aber auch gar nicht so viel Gedanken drüber machen, da nach aktuellem Plan eh der Großteil der Großgruppendiskussion in kleinere Gruppen verlagert werden soll.

**Comment by dragetd** [comment]
Ich bin eher dafür Dinge nur aufzuschreiben, falls sie mal zu einem Konkreten Problem geführt haben.

Und soweit ich weiß, ist es noch nicht vorgekommen, dass jemand von den Handzeichen schwer verwirrt war. Bzw. wird in dem Fall eines kompletten Neulings dieser auch niemals auf unsere Seite oder GIT gucken. ;-)

OK. das ist jetzt bei dem Thema nix dramatisches und wir können den Link dazu werfen… sure, why not. (PRs welcome)
Aber ich bitte inständig darum, daraus keine große Diskussion zu machen, es sei den jemand empfindet zu tiefst, dass wir die Handzeichen falsch nutzen und darüber sprechen müssen. xD

**Comment by dragetd** [comment]
Na gut, da niemand Anderes meine Bedenken teilt, merge ich den PR mal. :)

**Comment by Eisfunke** [comment]
Es ist zwar zu spät (sorry, SoPra), aber ich teile eindeutig @dragetd's Bedenken. Den Link finde ich okay, damit Neueinsteiger nachlesen können, was es da denn so gibt (wobei ich bezweifle, dass das oft passieren wird und ihn der Einfachheit halber lieber weggelassen hätte).

Das reicht dann aber auch. So was häuft sich sonst ganz schnell auf, und Bürokratie hat die Eigenschaft, nur zu wachsen und nie zu schrumpfen, also lasst uns bitte von Anfang an Wachstum möglichst vermeiden. Kleine Warnung für die Zukunft.

Zum "direkt dazu"-Handzeichen: Ich hatte nie den Eindruck, dass das bei uns ein Problem ist oder den Diskussionsfluss stört, das tut nur ganz ohne reinreden.

**Comment by Scosh** [comment]
Ich verstehe nicht ganz, wieso ihr beide euch jetzt gerade *hierbei* solche Gedanken macht, dass die Doku plötzlich den "zu viel" Punkt erreicht hat, aber die grundsätzliche Sorge kann ich durchaus nachvollziehen.

Es wäre schade, wenn die FOSS-AG zur Orga-AG wird, aber die Handzeichen aufzuzeichnen sollte ja nur als **Hilfestellung** dienen, **nicht eine fest in Stein gemeißelte Regel werden**, die man dann bürokratisch und autoritär allen Menschen bei den Treffen irgendwie aufzwingen muss … :D 

Unsere Orga-Guidelines sind daher ja auch grundsätzlich als **"Richtlinien"** (i.e. *guidelines*) und **nicht als Regeln** formuliert. So habe ich sie zumindest auch immer verstanden. Als nützliche Referenz und nicht Etwas, dass je als statisches, unflexibles Gesetz gesehen werden sollte.

**Comment by Scosh** [comment]
Außerdem ist das besprochene Dokument ohne den durch David jetzt eingefügten Link doch viel eher missverständlich, oder nicht? *Handzeichen* kann ja erst einmal vieles heißen (mit dem Zeigefinger auf jemanden zeigen oder jemandem den Mittelfinger geben sind auch Handzeichen).

Es ist so auf jeden Fall klar, dass schon eher bestimmte Handzeichen für Redekreise gemeint sind.

**Comment by dragetd** [comment]
Als Erklärung wie ich das meine:
Es gibt irgendwie zwei Aspekte.
- Der eine ist die 'Festlegung' von Dingen bei uns. Und da ziehe ich die Linie bei Dingen, die ein Problem waren. Wenn es nie zu Meinungsverschiedenheiten bei einem Punkt gekommen ist, muss man den IMHO auch nicht aufschreiben. Zu viel Micromanagement und pseudo-'Regeln' verderben nur die Motivation meiner Meinung nach. Alles was bis jetzt in diesem Repo steht, war zumindest schonmal Teil einer längeren oder kontroversen Diskussionen. Handzeichen (also deren Verwendung, nicht diese Doku-Diskussion) waren AFAIK noch kein Problem.

- Der andere Punkt ist ein 'Einstieg' für Anfänger. Aber das wird man neuen Leuten einfach mündlich sagen… die werden *NIE* von alleine auf diese Seite gucken. Wenn wir vielleicht mal eine Webseite haben und es da drauf pinnen… okay… vielleicht wird es der ein oder andere da entdecken. Ich versuche Dinge immer nach dem Standpunkt zu bewerten 'Wie bringt es die FOSS-AG voran?'. Und alles an 'Overhead' zu minimieren.

PS: Ich finde es cool, dass wir schriftlich, online mal diskutieren. ❤
PPS: Das Issue wurde durch den PR geschlossen… sollen wir es wieder öffnen, damit die Schnarchnasen die im Chat nicht mitlesen das auch eher 'entdecken'? :)

**Comment by Lazalatin** [comment]
Ich denke das wir diesen Punkt erst mal nicht weiter verfolgen müssen.
Wenn es keine Gegenstimmen gibt, soll es dabei bleiben :)
