### ISSUE TITLE
Öffentlich Kalender

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#28]
Wir haben letzte Sitzung festgestellt, dass unser Kalender nicht von jedem einsehbar ist. Da wir keine geheimen(?) Termine haben, sollte man den öffentlich machen.

**Comment by dragetd** [comment]
Innay war so lieb und hat einen öffentlichen Link generiert:
https://cloud.foss-ag.de/index.php/apps/calendar/p/Rs4BXqPkfyxJa2QK/FOSS-AG

Wer hat Lust den mit einem PR irgendwo anzuhängen? :-)

**Comment by InnayTool** [comment]
war jz vermutlich schwieriger diesen Issue zu schreiben, als einfach den Pull-request zu machen ^^

**Comment by dragetd** [comment]
Andere sollen auch mal arbeiten! :-P

**Comment by InnayTool** [comment]
Da kommt aber keine Freunde auf.
