### ISSUE TITLE
Umstruktirierung der Matrix-Kanäle

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#31]
Hallo zusammen,

ich wollte mal hier einen Vorschlag zur Neustrukturierung unserer Matrix-Kanäle unterbreiten, damit dieser schon vor Donnerstag ein wenig diskutiert werden kann.

Im Moment sagen unsere Guidelines, dass der Orga-Kanal nur für Aktive ist.
Wir müssten eigentlich *viel* mehr Leute als Aktive aufnehmen, da wir ansonsten Leute ausschließen, die nicht im Kanal sind und evtl. etwas von der Planung mitbekommen wollen. Gleichzeitig wollen wir auch interne Dinge privat besprechen können die nur Leute betreffen, die auch wirklich aktiv die Aktionen machen. 
Damit einher geht ja auch z.B. NextCloud Zugriff, was datenschutzrechtlich relevant ist. IMHO: Mit sehr vielen Leuten erhöht sich die Wahrscheinlichkeit von Problemen und verringert sich die Produktivität.

Folgender Vorschlag:

Geschlossene Kanäle (für private Dinge)
* 'FOSS-AG Privat' (Umbenennung von 'FOSS-AG Orga' oder Neuerstellung)

Offene Kanäle (für jeden):
* FOSS-AG Dortmund (Bleibt)
* FOSS-AG Organisation (neu erstellt)

Die Semantik des 'Aktive' Kanal wäre die vom aktuellen 'Orga' Kanal: Private Themen, datenschutzrechtliche Inhalte oder sonstige interne Themen die nicht direkt öffentlich sein sollen.

RFC! :-)

**Comment by ThiefOfTime** [comment]
Für mich stellt sich jetzt grad die Frage, was genau der Organisations Kanal dann für eine Funktionalität hat und ich bräuchte eine präzisere Umschreibung des Aktiven Kanals.
Ich persönlich bin dafür, dass in einem der Kanäle nur Sachen besprochen werden, wie sie aktuell für den Organisations Kanal in den Guidelines stehen. Diesen Kanal würde ich dann geschlossen handhaben, dort passiert nichts spannendes, abgesehen von Themen, die sich um Kaffee, Steckerleisten und co. drehen. Entsprechend wird niemand ausgeschlossen.
Den anderen Kanal würde ich öffentlich machen und würde darüber unsere gesamte richtige Orga schieben. Dieser Kanal kann gerne nur für Aktive sein. Dabei muss aber unsere Definition von "aktiv" angepasst werden. Mein Vorschlag:
Als "aktiv" gilt, wer sich entweder in den sitzungen einbringt, oder aber bei mindestens einem projekt aktiv mit organisiert. Um in die Gruppe (die sich um organisatorisches dreht), müssen alle bisher aktiven damit einverstanden sein (also wie bisher).
Ich würde es dennoch so beibehalten, dass es in jeder Gruppe Moderatoren gibt, die auch mal jemanden auf schlechtes Verhalten (auch destruktives) hinweisen.

**Comment by dragetd** [comment]
Der erste Teil entspricht doch irgendwie genau meinem Vorschlag, oder ich verstehe dich falsch. o.o

Und auch die 'Aktiven' Definition deckt sich irgendwie mit der existierenden: 'Beteiligt oder Beteiligte sich in den letzten Monaten aktiv an min. einem Projekt und nimmt regelmäßig an Sitzungen teil.'

Was übersehe ich? o.o

**Comment by ThiefOfTime** [comment]
Ich wollte nur sicher gehen, dass ich das richtig verstanden habe :D

Aktuell steht in den guidelines, dass ein aktives Mitglied neben seiner aktiven Teilnahme an Projekten oder Sitzungen, auch regelmäßig in den Sitzungen sein soll. Diesen Teil würde ich streichen. Eine regelmäßige, produktive und aktive Teilnahme an den Sitzungen, oder aktive Teilnahme an Projekten, würde ich als aktiv bezeichnen

**Comment by ROYALBEFF** [comment]
Für den Zugang zum Orga-Kanal würde ich keinerlei Einschränkungen setzen. Jeder der rein mag, sollte auch rein dürfen, da dieser Kanal sowieso nur dafür genutzt werden sollte kleine organisatorische Dinge wie das Mitbringen von Kaffee und Mehrfachsteckdosen zu organisieren. Die wirklichen organisatorischen Dinge werden im öffentlichen FOSS-AG Kanal bzw. in der entsprechenden Projektgruppe besprochen. Es wäre allerdings eine Überlegung wert, ob man den Orga Kanal umbenennt.

**Comment by InnayTool** [comment]
Hm, is ja ganz nett, dass Leute dann alles mitbekommen, aber wollen die das auch? Interessiert Außenstehende unser Gebikeshede?

**Comment by Lazalatin** [comment]
Ich plädiere dafür die Anzahl an Kanälen gering zuhalten.
Wir sollten den Orga Kanal entsprechend umbenennen (FOSS-AG Organisation) und diesen wie vorgeschlagen öffnen. Der "FOSS-AG Dortmund" Kanal bleibt und gut ist. Ein privater Kanal scheint mir obsolet, dafür gibt es noch die Gruppenkanäle und außerdem kann bei Bedarf ein Direktchat oder ein temporärer Gruppenchat eröffnet werden.

Ansonsten fühlt euch frei die Richtlinien anzupassen. Wenn wir aber die Aktiven entfernen und den Organisationskanal öffnen bleibt die Frage nach der Verantwortung. Solange wir eine AG sind gibt es da wenig Probleme, denn letztendlich trägt die Fachschaft die Verwantwortung. Sobald wir aber eine eigene juristische Person sind, haben wir mehr Probleme. Spätestens dann muss es eine Art Vorstand geben!

**Comment by ROYALBEFF** [comment]
Wir sollten vom Ist-Zustand ausgehen und da liegt die Verantworung nunmal bei der Fachschaft. Ich halte es für unproblematisch den Channel zu öffnen.

**Comment by Lazalatin** [comment]
@ROYALBEFF Jain, natürlich ist es aktuell unproblematisch. Aber der Ist-Zustand ist eben nur eine Momentaufnahme. Wir sollten uns Gedanken um die Zukunft machen. Ich werde dazu beizeiten mal ein Issue eröffnen, das kann ja dann ne Weile da sein und wir spammen hier nicht rum :+1:

**Comment by Eisfunke** [comment]
Also ich finde es okay, die Orga-Gruppe zu öffnen, bin mir aber nicht so sicher, ob ich nicht doch gerne ein Veto-Recht für Neuzugänge hätte. Aber wir können es von mir aus auch erst mal ganz aufmachen und falls es Probleme damit geben sollte, dann noch reagieren.

Sollte sich herausstellen, dass doch eine private Gruppe notwendig ist, können wir wieder eine einführen, das glaube ich aber erstmal nicht, also können wir das mit der Öffnung gerne so lassen.

**Comment by InnayTool** [comment]
was heißt denn Öffnung?
und was machen wir mit den Sachen, die jz Datenschutzrelevant oder irgendwie doch privat sind?

**Comment by davidmehren** [comment]
Also ich hätte gerne einen Kanal für Internes. Sei es jetzt um externe nicht öffentliche Themen zu diskutieren, Dateien zu tauschen oder einen Verantwortlichen für Schlüssel zu finden.

Die Orga-Dinge könnte man einfach im normalen Kanal machen, aber wenn ihr da die Gefahr Menschen zu nerven als zu groß einschätzt, kann das auch separat.

**Comment by Eisfunke** [comment]
@InnayTool "Öffnung" meinte das, was Chef vorschlug - keine Einschränkungen mehr für den Orga-Raum.

**Comment by dragetd** [comment]
Der aktuelle PR beschreibt einen offenen Raum 'FOSS-AG Dortmund' und einen offenen Organisations-Raum 'FOSS-AG Organisation'.

Auf Wunsch von @Lazalatin  gibt es keinen dritten, geschlossenen Raum 'FOSS-AG privat'. Aber wenn @Lazalatin nicht so viele Räume mag, dann soll er einfach nicht in den Raum reingehen, dann hat er einen Raum weniger. :-P

**Comment by Lazalatin** [comment]
> Also ich hätte gerne einen Kanal für Internes. Sei es jetzt um externe nicht öffentliche Themen zu diskutieren, Dateien zu tauschen oder einen Verantwortlichen für Schlüssel zu finden.

Also ich sehe da nun nicht so den Bedarf. Entweder sind $Dinge so unkritisch dass sie in einem öffentlichen Orga Kanal geklärt werden können (AKA Wer hat/nimmt den Schlüssel?) oder sie sind so kritisch dass sie unter einer Untermenge von Personen geklärt/getauscht werden können (So wie z.B. Fotos von dem Projekttag oder Workshop einer Untergruppe)

@dragetd Ja, natürlich könnte ich in den privaten Raum auch einfach nicht reingehen, du unterschlägst hier aber das was ich dir schon via PN sagte: FALLS ein privater Raum mit einer ausgewählten Menge Leuten nötig ist, ist die Existenz des aktuellen invite-only Orga Raums völlig ausreichend und wir müssten den PR ablehnen und die Diskussion nochmal vollkommen von vorne aufziehen. (IMHO)

**Comment by InnayTool** [comment]
also ich glaube ich bin @davidmehren  Meinung

**Comment by Lazalatin** [comment]
> also ich glaube ich bin @davidmehren Meinung

@InnayTool Ich hätte mir dafür zwar auch Argumente gewünscht aber gut, ich plädiere erneut:
Ein dritter Kanal ist gelinde gesagt Unfug, die Diffusion von Kommunikation auf drei Räume ist unnötig. Im besten Falle verringern wir uU das Aufkommen an Text pro Raum, aber das dient nicht der Übersichtlichkeit. Falls der Vorschlag von @davidmehren wirklich so viel Anklang finden sollte, werde ich auf mein obiges Argument verweisen und vorschlagen, die Diskussion zurückzusetzen und den PR soweit abzuwandeln, dass er vorerst keine Räume neu regelt. Es ergibt einfach in keinem mir vorstellbaren Szenario Sinn zwei öffentliche Kanäle zu haben, welche de facto gleichen Inhalt besitzen (bis auf +orgazeug) und dann NOCH einen Raum für vertrauliches Getuschel. Denn den Raum für Orga-Kram + vertrauliches Getuschel haben wir bereits. Zudem habe ich >5 Räume für Untermengen von vertraulichem Getuschel -> Gruppenräume. Da ist kein Mehrwert vorhanden wenn da noch ein weiterer Raum hinzukommt.

**Comment by ThiefOfTime** [comment]
auch wenn mich ein dritter Raum nicht stören würde, sehe ich auch keinen Mehrwert in einem dritten Raum. Alles was wir machen kann öffentlich getan werden oder aber (wie Bilder) in einem kleinem Kreis von Personen verteilt werden. Egal ob es sich um Kaffee holen handelt, oder aber um die Strukturierung der AG, beides sind Orga Themen. Die Trennung (damals) entstand nur dadurch, dass wir alle anderen in dem anderen FOSS AG Channel nicht zu spammen und es bei reinen Diskussionen und sonstigen Themen bleibt. Die, die sich am Organisatorischen beteiligen wollen, die wird das bisschen auch nicht stören. Sollten wir einen dritten Kanal haben wollen, dann plädiere ich darauf, dass dort auch wirklich NUR sowas besprochen wird, wie Kaffee holen. Sodass es so oder so nicht zwingend notwendig ist in dem Raum zu sein und man auch somit die Entscheidung hat dort drin zu sein. Alles andere würde ich öffentlich in dem normalen FOSS AG Orga Raum machen. Das Verteilen von privaten Bildern können wir auch über andere Wege erreichen und das Verbreiten von persönlichen Informationen ebenfalls.

**Comment by dragetd** [comment]
@Lazalatin Der Wunsch besteht aber von einigen Leuten. Warum stört dich die Existenz eines Raum denn so? Wenn du da nicht rein willst, dann ist das doch OK. Der *einzig* relevante (im Sinne der FOSS-AG) Raum wäre eh der (offene) Orga Raum (und die eizelnen Projekt-Räume). Den Rest könnte jeder Nutzen wie er will.

Auch die Aussage 'Es ergibt einfach in keinem mir vorstellbaren Szenario Sinn zwei öffentliche Kanäle zu haben, welche de facto gleichen Inhalt besitzen' kann ich nicht nachvollziehen. Der allgemeine Kanal ist ein sehr allgemeiner OpenSource Chat Kanal geworden. Der Orga Kanal wäre für Orga. Ich sehe da einen sehr deutlichen Unterschied in den Inhalten.

Ich will das Eingangs erwähnte nochmal wiederholen: Der einzig wirklich relevante Kanal wäre der öffentlich Organisationskanal. Wieso wäre es schlimm, wenn einige sich auch einen privaten machen?

**Comment by Lazalatin** [comment]
@dragetd Weil du damit über das Ziel hinausschießt da das zu großer Wahrscheinlichkeit de facto bereits der Fall ist. Ich finde dass man das daher als Diskussionspunkt droppen kann. Mehr sage ich damit nicht aus.
Ich habe aber momentan auch ein bisschen den Topic aus den Augen verloren. Ich gebe später vllt nochmal mehr Senf.

**Comment by davidmehren** [comment]
Ich versuche mal die angesprochenen Varianten der Raumstruktur aufzuzählen:
1. die aktuelle Lösung
	- "FOSS-AG" für Diskussionen
	- "Orga" (privat) für interne & Orgadinge
2. Orgasachen öffentlich
	- "FOSS-AG" für Diskussionen und Orga
	- "intern" (privat) für ausschließlich interne Dinge
3. Orgasachen öffentlich aber separat
	- "FOSS-AG" für Diskussionen
	- "Orga" für Orgadinge
	- interne Sachen sollen hier in ad hoc erstellten Räumen besprochen werden
4. Orgasachen öffentlich aber separat plus ein Raum für internes
	- "FOSS-AG" für Diskussionen
	- "Orga" für Orgadinge
	- "intern" (privat) für ausschließlich interne Dinge

Im folgenden mache ich mal 4 Kommentare für die Varianten, jeder der mit der entsprechenden Variante leben kann, betätige bitte den "Daumen nach oben".

**Comment by davidmehren** [comment]
Variante 1

**Comment by davidmehren** [comment]
Variante 2

**Comment by davidmehren** [comment]
Variante 3

**Comment by davidmehren** [comment]
Variante 4

**Comment by ThiefOfTime** [comment]
Ich gebe der Variante 2 mal einen Daumen hoch, allerdings nur unter der Prämisse, dass wir hier davon sprechen den Orga offen zu machen, sprich jeden in den Kanal lassen und nicht nur die Orga transparenter zu machen. @davidmehren dein Kommentar von #32 hat mich dahingehend irritiert

**Comment by davidmehren** [comment]
Hä?! In Variante 2 werden Orgadinge im (eh schon offenen) normalen FOSS-AG Kanal gemacht. Transparenter geht es wohl kaum.

**Comment by ThiefOfTime** [comment]
Schon gut, dann ziehe ich meine Stimme zurück :D

**Comment by fes0j** [comment]
Für mich ist eigentlich nur wichtig, dass der bisherige Orga-Kanal nicht nachträglich öffentlich wird.
Ansonsten kann ich mich (nach dem die entsprechenden Details geklärt sind) mit allen 4 Varianten arrangieren.

**Comment by ThiefOfTime** [comment]
das ein neuer Kanal geöffnet wird, wäre glaube ich eh eigentlich die beste Lösung, da es mind. 2 Leute gibt, die mit der History des alten Kanals unzufrieden sind und einen neuen Kanal zu machen, alle dort hin zu portieren und den alten zu schließen haben wir ja schon mal gemacht :D sollte also nicht so das Problem sein :)

**Comment by davidmehren** [comment]
In der Sitzung wurde die Umfrage ausgewertet und damit die Umsetzung von Variante 4 beschlossen.

**Comment by Lazalatin** [comment]
As #35 has been merged this issue can be closed (until further discussion is needed)
