### ISSUE TITLE
Definition von "aktiven Mitgliedern" oder "Mitgliedern" im Allgemeinen

### ISSUE THREAD

**Issue by lxndio** [foss-ag/orga_guidelines#32]
Wie schon in der Sitzung besprochen, kann jetzt hier über aktive Mitglieder bzw. Mitglieder im Allgemeinen diskutiert werden.

Meine Meinung folgt auch noch...

**Comment by ROYALBEFF** [comment]
Ich würde die Unterscheidung zwischen aktiven Mitgliedern und Mitgliedern abschaffen. Angenommen der Orga Kanal würde wie [hier](https://github.com/foss-ag/orga_guidelines/issues/31) von mir beschrieben genutzt werden, so würde man nur noch unterscheiden zwischen Personen, die an AG relevanten Abstimmungen teilnehmen dürfen und diesen, die es nicht dürfen. Stimmberechtigt sollte jeder werden dürfen. Dieses Recht vergeben wir allerdings nicht von uns aus, sondern die betroffene Person muss, sofern sie dieses Recht erhalten mag, dieses z.B. im Rahmen einer Sitzung anfragen. Die bereits Stimmberechtigten können dann darüber diskutieren (in welchem Rahmen auch immer) und entscheiden, ob sie der entsprechenden Person genügenden Vertrauen entgegenbringen, um ihr dieses Recht zu geben. Weitere Rechte wie der Zugriff auf die Cloud und den Zugriff auf das Git kann man dann so vergeben wie sie nötig sind.

**Comment by Eisfunke** [comment]
Wo/wie würden wir denn festhalten, wer "stimmberechtigt" ist?

**Comment by dragetd** [comment]
Wir könnten das mit der GitHub und Gittea-Organisation verknüpfen. Oder es uns einfach merken. xD

**Comment by Lazalatin** [comment]
Man kann das vllt einfach in die Protokolle übernehmen? So eine "Berechtigtenliste" einfach immer mitschleppen?

**Comment by InnayTool** [comment]
Das letzte is aus meiner Sicht ein schrecklicher Vorschlag ^^

**Comment by Lazalatin** [comment]
> Das letzte is aus meiner Sicht ein schrecklicher Vorschlag ^^

Hätte aber den unheimlichen Vorteil, dass man immer sieht wer berechtigt ist und wer nicht. Es ist schon ein wenig besser als beispielsweise wieder eine Vermischung mit anderen Plattformen zu versuchen, welche unsere Struktur ohnehin nicht richtig abbilden können xD

@InnayTool Hast du vllt eine bessere Idee?

**Comment by ThiefOfTime** [comment]
Nur so als Vorschlag. Jeder, der sich an der Strukturierung der AG beteiligen will und somit in den Orga Kanal kommt ist automatisch stimmberechtigt. Ein Veto hat die gesamte AG vereint. Es zählt dabei immer ein Mehrheitsentscheid, egal ob die Idee abgelehnt wird oder aber dieser zugestimmt wird. Natürlich sollte in der Situation dennoch geguckt werden, was genau die übrigen Personen stört und evtl findet man eine ergänzende Lösung mit der man alle zufrieden stellen kann.

**Comment by dragetd** [comment]
Da drehen wir uns doch wieder im Kreis! Der Vorschlag war den Orga-Kanal offen zu machen. Meines Verständnisses nach heißt das den Link dazu z.B. in den Subtitel vom Laber-Kanal zu packen.

Wenn der versteckt und nur auf Anfrage existiert, dann sind wir irgendwie wieder beim Status Quo, oder irre ich mich da?

**Comment by ThiefOfTime** [comment]
@dragetd ich sehe grad nicht ganz den Bezug zu deiner Antwort. Es geht auf jedenfall darum den Kanal öffentlich zu machen und nicht zu verstecken. Hier geht es ja erst mal nur um die Definition von aktiven Mitgliedern und Stimmberechtigung.

**Comment by dragetd** [comment]
Ja. Und unter der Prämisse, dass der Orga Kanal komplett offen ist, bin ich dagegen, dass eine Anwesenheit dort drin irgendetwas impliziert. Weder 'aktiv' noch 'stimmberechtigt'. xD

**Comment by ThiefOfTime** [comment]
Was wäre dein Vorschlag?

**Comment by dragetd** [comment]
Aktive -> streichen (siehe PR)
Stimmberechtigt -> ar­bi­t­räre Liste, wo auch immer geführt. Wobei ich auch nichts dagegen hätte, dieses Konzept ebenfalls zu streichen. Dann wäre die Rolle der Maintainer der 'Safeguard' für Einzelpersonen die Projektfortschritt und Abstimmungen torpedieren.

[edit] Wobei ich durchaus gerade bemerkt habe, dass ein 'Streichen' der Stimmberechtigten dann in der Umsetzung doch @ThiefOfTime's Idee entspricht. Wäre das vielleicht eine Lösung?

**Comment by Lazalatin** [comment]
Ich versuche hier mal @davidmehren wiederzugeben, wenn ich sage: Dieses Issue ist eigentlich unsinnig, da wir hier Wortklauberei betreiben, die keine echte Änderungen hervorrufen wird, solange wir nicht umsetzen worüber wir reden.
Ich persönlich stimme in Teilen zu, wobei ich der Ansicht bin, dass wir ruhig mal einen anderen Begriff wagen können ;)

**Comment by ThiefOfTime** [comment]
Dann lässt es uns tun. Wagen wir das bisher besprochene Und nehmen dazu noch einen neuen Begriff

**Comment by davidmehren** [comment]
Mal davon abgesehen, das ich das Umbenennen von "aktives Mitglied" in "Stimmberechtigte Person" für wenig sinnvoll halte, gibt es noch ein weiteres Problem:

Wenn wir die Hürde aktives Mitglied zu werden aufweichen, wird es immer schwerer Entscheidungen zu treffen. Es ist ja (offensichtlich) jetzt schon schwer genug alle Menschen zu motivieren, sich an Entscheidungen zu beteiligen. Das würde mit mehr Stimmberechtigten dann sicher nicht einfacher werden.

Daher meine Meinung: diesen Punkt so lassen wie er aktuell ist. Die Orga-Transparenz können wir gerne verbessern, aber dafür gibts ja #31

**Comment by Lazalatin** [comment]
Ich unterstütze @davidmehren in seinen Ansichten. Umbenennung wird keinen Effekt bringen, ich vermute dass dies einfach durch Vermischungen mit #31 entstanden ist. Ich würde dieses Issue und den korrespondierenden PR ablehnen.

**Comment by Lazalatin** [comment]
Da entgegen meiner Annahme kein aktueller PR existiert und wir nach meinen Informationen noch weiteren Diskussionsbedarf haben, entferne ich dieses Issue aus dem aktuellen Milestone und stelle dieses für die nächste Iteration zurück.

**Comment by Lazalatin** [comment]
Obsolet durch #37 #38 und #39
