### ISSUE TITLE
Notwendige Bedingungen für „aktive Mitglieder“

### ISSUE THREAD

**Issue by davidmehren** [foss-ag/orga_guidelines#37]
Aktuell ist Bedingung um „aktives Mitglied“ zu werden das Folgende:

> Beteiligt oder Beteiligte sich in den letzten Monaten aktiv an min. einem Projekt und nimmt regelmäßig an Sitzungen teil.

Wollen wir das in irgendeiner Weise ändern?

**Comment by davidmehren** [comment]
Ich bin dafür die Formulierung entweder beizubehalten oder eine hartkodierte Bedingung zu entfernen und einfach „Wurde von der Mehrheit der aktiven Mitglieder zum aktiven Mitglied gewählt" zu schreiben.

**Comment by ThiefOfTime** [comment]
Ein aktives Mitglied sollte nicht gewählt werden und so wie wir es aktuell vermerkt haben ist es nicht mehr praktikabel. Mein Vorschlag: ein aktives Mitglied ist jemand, der sich an Projekten der ag beteiligt/beteiligte oder sich regelmäßig bei Sitzungen konstruktiv einbringt oder aber sich konstruktiv an der Organisation der ag beteiligt.

**Comment by davidmehren** [comment]
Naja, irgendwas/irgendwen brauchen wir aber, um zu überprüfen, ob die Person die Bedingungen erfüllt. Auch bei deinem Vorschlag @ThiefOfTime.

**Comment by lxndio** [comment]
Es wurde ja gestern (14.06.) in der Sitzung vorgeschlagen, von wem auch immer, dass man möglicherweise im privaten Chat darüber abstimmen könnte, wer zu einem aktiven Mitglied "befördert" wird. Das ist, meiner Meinung nach, aus verschiedenen Gründen nicht umsetzbar.

Allerdings finde ich, dass jedem die Möglichkeit zustehen sollte, begründet Einspruch dagegen zu erheben, dass eine Person aktives Mitglied wird, aus welchen Gründen auch immer das notwendig werden sollte. Natürlich dürfen hier nur triftige Gründe aufgeführt werden und nicht solche Dinge, wie "ja, ich mag den halt einfach nicht".

Mein Vorschlag wäre daher, dass man die Definition in soweit abändert, wie @ThiefOfTime das auch schon vorgeschlagen hat, wobei ich eher einen Schwerpunkt auf die "aktive Beteiligung", als auf irgendetwas genau setzen würde. Also möglicherweise:

_"Aktives Mitglied ist, wer aktiv zur AG beiträgt, sei dies durch regelmäßige und konstruktive Anwesenheit bei den Sitzungen, durch Beteiligung an Projekten oder auf eine andere Art und Weise."_

Außerdem würde ich aktive Mitglieder nicht auswählen, sondern einfach abwarten, dass jemand gerne aktives Mitglied werden möchte. Das heißt also, jemand kommt zur Sitzung und sagt "hey, ich denke ich erfülle die entsprechenden Kriterien und wäre gerne aktives Mitglied". Falls dann niemand Einspruch erhebt, entweder in der Sitzung oder auch intern im privaten Chat, ist diese Person dann aktives Mitglied.

**Tl;dr:**
- Aktiv = Regelmäßige, konstruktive Beteiligung an Sitzungen oder Beteiligung an Projekten etc.
- Keine Abstimmung zur "Beförderung", sondern das Recht auf Einspruch.

Bitte um Feedback zu diesem Vorschlag.

**Comment by ThiefOfTime** [comment]
Das einzige, was mich an der alten Formulierung stört ist das "und". Ansonsten wären sie immernoch super. Aber definieren wir es mal weiter. Überprüft wird dadurch, dass jemandem der AG das Engagement auffällt, dieses wird den anderen mitgeteilt und gut ist. Die Frage, die ich mir stelle ist, ob man die Rolle des aktiven Mitgliedes immernoch braucht, nach aktuellem Stand. Welche Privilegien hätte ein aktives Mitglied? (ich weiß anderes Issue) Jemand, der sich an einem Projekt beteiligt braucht evtl. Zugriff auf Dienste. (anderes Issue) Die Mitgliedschaft im Orga Kanal ist nicht mehr Teil davon, heißt es bleibt die Mitgliedschaft im Privaten Kanal und ein Prinzipielles Stimmrecht. Da ist aber auch wieder die Sache, dass Abstimmungen den einzelnen Gruppen überlassen sind, dafür ja die Unterteilung. Die Orga Gruppe ist eine Untergruppe wie jede andere. Es bleibt somit ein Veto-Recht, was mit dieser Rolle einhergeht.
Wenn ich das mal aus meiner Sicht zusammenfasse, ist ein "aktives Mitglied" jemand, der in den Privaten Channel darf und Veto-Recht hat mehr nicht. Für den Fall, dass wir das "aktive Mitglied" so definieren, wäre ein „Wurde von der Mehrheit der aktiven Mitglieder zum aktiven Mitglied gewählt" für mich ok. Ich werde aber auch noch mal weiter drüber nachdenken

**Comment by ThiefOfTime** [comment]
@lxndio Ich bin auch für ein Veto-Recht, lieber als für eine Abstimmung. Das mit dem, dass die Person von selbst auf uns zukommen muss, ist schwer, weil der Person in den meisten Fällen nicht klar ist, ob sie die Bedingungen erfüllt.

Bzgl. des Vorschlages "möglicherweise im privaten Chat darüber abstimmen könnte, wer zu einem aktiven Mitglied "befördert" wird": Dafür ist der Private Chat nicht da. Das hat nichts im Privaten Chat zu suchen. Im Privaten Chat kann gesagt werden, dass man seine Bedenken bzgl. der Person hat, aber der Channel ist nicht für Abstimmungen da. Zumindest aus meiner Sicht. Der Channel ist für Private Themen, Bilder, etc.. Eine Abstimmung über die Aufnahme eines aktiven Mitgliedes ist meines erachtens Orga related.

**Comment by dragetd** [comment]
Meines Erachtens nach suggeriert 'aktiv', dass jemand der nicht eine solche Rolle hat, nicht aktiv ist. Das ist IMHO eins der großen Probleme des Begriffes. Für mich ist jeder der regelmäßig teilnimmt *oder* viel macht auch automatisch aktives Mitglied. Da stimme ich @ThiefOfTime zu, dass man aus dem 'und' oder 'oder' macht.

Noch lieber wäre es mir aber, die Rolle komplett zu streichen. Weil wir es in der Diskussion nicht schaffen Bedingungen, Begrifflichkeit und damit einhergehende Verantwortungen voneinander zu trennen, wie wir auch in der Sitzung bemerkt haben.

**Comment by ThiefOfTime** [comment]
ich stimme @dragetd zu. Ich bin ebenfalls für die Streichung der Rolle des aktiven Mitgliedes. Denn Alles was für dieses an Special Kram übrig bleibt kann entweder unter einem anderen Namen zusammen gefasst werden oder aber Prinzipiell komplett gestrichen werden. Eine Lösung ist auch, dass in den einzelnen Gruppen geguckt wird, wer sich noch aktiv an einem Projekt beteiligt und ansonsten entsprechend aus der Gruppe gebeten wird um z.B. besser Planen zu können wie viele Leute einem noch Helfen können. Das gleiche gilt für die Orga Gruppe. Ist also jemand Mitglied in einer solchen Gruppe, ist er sogar direkt nach definition ein "aktives Mitglied". Die Rolle an sich kann also per se entfallen. Ist nur so eine spontane Idee

**Comment by avahenriette** [comment]
Ich würde die aktive Rolle komplett streichen und stattdessen einen Begriff finden der genau das wiederspiegelt was wir in dem anderen Issue unter den Bedingungen auffassen. Darunter fällt das Stimmrecht, sowie der private Chat und alles was unter diesem fällt (Datenschutzangelegenheiten usw. ). Wir sollten einen Begriff finden wie beispielsweise "verantwortliches Mitglied", da dieser die bereits genannten Bedingungen( ist aber auch ein anderes Issue, also keine weitere Erläuterung ) beschreibt. Des Weiteren bin ich dafür, dass es beide Möglichkeiten des Eintritts in diese Mitgliedschaft gibt: 1. Man wird im Privatchat vorgeschlagen und 2. Die besagte Person kann auf die Anwesenden zugehen und sich über die Mitgliedschaft erkundigen. Wir sind eine offene AG. Das möchte ich an dieser Stelle betonen um meinen Vorschlag, beide Möglichkeiten des Eintritts, zu untermauern. 

Verzeiht mir, wenn ich erst Stunden bis ein oder zwei Tage später antworten kann. Zur Zeit habe ich nahezu kein Internet.

**Comment by davidmehren** [comment]
**Eins vorweg**
Ich habe das Gefühl, das nicht ganz klar ist, worum es hier geht. Eine Streichung der Rolle ist Schwachsinn, weil wir zugleich eine neue Rolle schaffen würden (nämlich wahrscheinlich die des viel genannten "Stimmberechtigten").
Daher bitte ich darum, das Konzept der drei Issues zu befolgen.
Wenn am Ende ein Stimmberechtigter rauskommt, der nur zusätzlich im internen Chat ist um Datenschutzangelegenheiten zu regeln, sei es so. Das lässt sich aber auch im aktuellen Verfahren umsetzen, es besteht keine Notwendigkeit schon wieder was Anderes zu machen.


**Zum Inhaltlichen**
Mit der Idee von @lxndio könnte ich auch leben. Formulierungsvorschlag:


> Hat sich - ohne Veto eines anderen aktiven Mitglieds - in einer Sitzung für die aktive Mitgliedschaft beworben.

Damit würden wir die Bedingungen nicht hartkodieren, sondern könnten von Fall zu Fall entscheiden. Falls wir stattdessen Sachen fest aufschreiben wollen, geht das natürlich auch, hier wäre der angesprochene Austausch von „und“ durch „oder“ dann zu diskutieren.

Stichwort Abstimmungen im privaten Chat: Je nachdem was konkret man gegen die Aufnahme einer Person hat, macht es natürlich Sinn, das nicht öffentlich anzubringen. Das kann aber wohl jeder selber bewerten.

Stichwort "die Leute wissen nicht, dass es die Rolle des aktiven Mitglieds gibt":
Das ist natürlich theoretisch ein Problem, wenn man sich eigentlich aktiv „bewerben“ muss. Wenn jemand sich bei uns viel einbringt, sind wir aber wohl auch in der Lage der Person mitzuteilen, dass sie das vielleicht mal tun sollte
Ist also in der Praxis leicht lösbar.

**tl;dr**
- Please stay on topic. Wir haben das Thema nicht ohne Grund dreigeteilt.
- Bedingung für eine „aktive Mitgliedschaft“ gerne weglassen und einfach im Einzelfall entscheiden.


_Ich weise darauf hin, dass man sich oben gerne statt „aktives Mitglied“ auch „stimmberechtigtes Mitglied“ oder wasauchimmer denken kann._

**Comment by Lazalatin** [comment]
Ich glaube dass dieser Punkt inzwischen so weit fortgeschritten ist, dass er kommenden Donnerstag zur Abstimmung gebracht werden kann.

_Was nicht zuletzt daran liegt, dass ich selbst nichts mehr konstruktiv zu ergänzen habe, sondern nur noch eine Meinung darlegen könnte._

Ich freue mich schon auf den ersten Schritt zur Neuorganisation in der kommenden Woche.
**Natürlich darf solange munter weiterdiskutiert werden!** :+1:

**Comment by davidmehren** [comment]
@Lazalatin Was sind denn deiner Meinung nach die Abstimmungsmöglichkeiten die man nächsten Donnerstag anbringen könnte?

**Comment by ROYALBEFF** [comment]
@avahenriette 
Prinzipiell bin ich ganz an deiner Seite, allerdings finde ich es kritisch, wenn wir Leute für den privaten Chat/ das Stimmrecht oder was auch immer vorschlagen, da man damit unbewusst vermutlich Leute ausgrenzt. Es entstehen dadurch Konflikte wie: Person A wurde vorgeschlagen, aber Person B nicht, obwohl beide ungefähr eine gleiche Rolle in der AG spielen. Das könnte für unangenehme Spannungen sorgen. Wir sollten jedoch darauf achten, dass es jedem klar, dass die Möglichkeit der Anfrage besteht.

**Comment by avahenriette** [comment]
@ROYALBEFF genau deshalb bin ich für beide Möglichkeiten des Eintritts. So ist es zugelassen, dass Person B aus deinem Beispiel einen der bereits "aktiven" Mitglieder anspricht und fragt, wie auch er/sie/whatever eines dieser Mitglieder sein kann.
Mir ist es wichtig, dass diese Entscheidungen ein Miteinander aus beiden Parteien ( die die über die jeweilige Person entscheiden und die über die entschieden wird ) ist. 
Es ist also als Zusatz für genau die genannten Fälle aufzufassen.
