### ISSUE TITLE
Rechte von „aktiven Mitgliedern“

### ISSUE THREAD

**Issue by davidmehren** [foss-ag/orga_guidelines#39]
Die Rechte von „aktiven Mitgliedern“ sind momentan wie folgt definiert:

> Ist Member in der GitHub-Organisation. (kann also insbesondere neue Repos erzeugen)

> Bekommt Zugriff auf weitere Dienste der FOSS-AG.

> Wird Mitgliedschaft im Orga-Chat angeboten.

Wollen wir dies irgendwie ändern?

Blocked by #37 #38

**Comment by ThiefOfTime** [comment]
Die Mitgliedschaft im Orga Chat ist ab jetzt eh als Punkt obsolet.
Wir hatten schon mal als Vorschlag, dass wir die Rechte an den AG Diensten, wie z.B. Github nach Bedarf vergeben werden. Wenn also ein Mitglied der FOSS-AG Zugriff auf einen Dienst braucht, wird darüber informiert/diskutiert und anschließend vergeben. Ich finde die Idee nicht verkehrt.

**Comment by davidmehren** [comment]
Bitte beachte das „blocked“ Label. Dieses Issue sollte erst nach Erledigung von #37 und #38 diskutiert werden.

**Comment by ThiefOfTime** [comment]
Ok, verstehe ich. Sehe ich aber als sehr problematisch an. Denn eine Abstimmung über wie soll jemand die Rolle eines aktiven bekommen, erfordert eine Definition darüber was genau einen aktiven auszeichnet, also was für Rechte bringt diese Bezeichnung?

**Comment by davidmehren** [comment]
Fixed by #41
