### ISSUE TITLE
Notwendigkeit der Rolle des "aktiven Mitgliedes"

### ISSUE THREAD

**Issue by ThiefOfTime** [foss-ag/orga_guidelines#40]
Nach der Öffnung des Orga Kanales hat die Rolle des aktiven Mitgliedes seine Relevanz verloren. Die Einzigen Verantwortungen, die ein "aktives" Mitglied noch hat, sind ein Veto-Recht (**kein** Mitbestimmungsrecht). Das Mitbestimmungsrecht gab es so nur in der Kombination mit der Orga Gruppe. Durch Öffnen dieser, haben alle, die Mitglied der Orga Gruppe sind, dort auch ein Stimmrecht. Da der Private Kanal nur für Private Dinge gedacht ist, wie Bilder o.ä., kann eine Person nur in diese Gruppe eingeladen werden, wenn alle damit einverstanden sind, da es sich um persönliche Daten handelt. Dies ist weder ein Privileg noch eine explizite Verantwortung. Eine Einladung in diese Gruppe mit dem aktiven Mitglied zu verbinden geht meiner Ansicht nach an dem Sinn der privaten Gruppe vorbei und führt uns nur wieder an die Anfangsproblematik.
Bleibt das **Veto**-Recht. Für dieses Person lässt sich immernoch eine Bezeichnung finden. Das einfachste ist, dass die Personen, die in einem Channel ein Veto recht haben, die sind, die diesen Channel Maintainen, so wie in jedem Channel. Meiner Ansicht nach ist die Rolle des aktiven Mitgliedes überflüssig und ich möche darüber abstimmen ob diese Rolle weiterhin verwendet/angepasst werden soll.

**Comment by ROYALBEFF** [comment]
Ich würde @ThiefOfTime teilweise zustimmen. Ich denke das die "aktive Mitglieder" Rolle nicht mehr notwendig ist. Das einzige was meiner Ansicht nach als Unterscheidungskriterium überbleibt ist die Stimmberechtigkeit. Von daher schlage ich vor eine Unterscheidung in Stimmberechtigt und Nicht-Stimmberechtigt einzuführen. Stimmberechtigt kann jeder werden der mag, allerdings sollten wir es vermeiden Personen das Stimmrecht anzubieten, sondern stattdessen klarmachen, dass Personen, die ihre Stimme abgeben wollen, sich an uns wenden. Die zu diesem Zeitpunkt stimmberechtigten Personen können dann bestimmen, ob die neue Person eine Stimmberechtigung bekommen soll. Das sollte eigentlich immer der Fall sein, außer es gibt drastische Gründe dagegen. Ich bin jedoch dagegen, dass wir feste Kriterien dazu festlegen und stattdessen jedes mal aufs Neue im Einzelfall entscheiden.

**Comment by ThiefOfTime** [comment]
Ich frage mich einfach in welchen Fällen, zu welchen Themen eine stimmberechtigung nicht erteilt werden kann. Denn an der Organisation (dem einzig kritischen) Thema darf sich jeder beteiligen. Auch bei Abstimmungen, ansonsten sind wir bei einem ähnlichen Problem Wie vorher auch. Ist es also wirklich sinnvoller ein Stimmrecht zu haben, als ein Veto recht. Und das Veto recht an einen wirklich kleinen Kreis an Leuten pro chat Raum geben. *maintainer hust hust*

**Comment by davidmehren** [comment]
Wir könnten es uns einfach machen: Die Rolle streichen.

Die Aufteilung entstand ja aus dem Gedankengang, dass wir uns einer „feindlichen Übernahme“ erwehren können müssen. Ich denke, das ist erstens höchst unwahrscheinlich und geht zweitens auch so.

Wie bereits geschrieben: Die Teams entscheiden eh intern, die Orga ist eh öffentlich. Wenn da wer Stunk verbreitet, können die restlichen Mitglieder sich auch so wehren.
Und an Abstimmungen nehmen einfach alle teil, die grade da sind.

Bliebe nur noch die Frage, wer in den Chatraum mit Datenschutzdingen darf. Könnte man aber einfach mit „alle bisherigen Mitglieder haben nichts dagegen” lösen.

_Meta: Jetzt habe ich mich selber nicht an die Struktur gehalten! Ahh!_

**Comment by ThiefOfTime** [comment]
Da der Orga Kanal sich ab jetzt verhält wie jeder andere Gruppen-Kanal ist ein "Stimmberechtigtes Mitglied" ein wenig obsolet. Wie in jedem Kanal haben wir einfach auch dort Maintainer, die sich um die Gruppe kümmern. Damit sollte eine feindliche Übernahme nicht so einfach funktionieren. 

Die Idee bzgl des Datenschutzraumes, die @davidmehren grad äußerte, finde ich echt gut.

Bzgl der Abstimmung würde ich nur gerne einwerfen, dass es wirklich einfach Mitglieder gibt, die nicht bei unseren Treffen dabei sein können. Oder aber Mitglieder, die einfach an diesem Termin nicht dabei sein können. Eine Abstimmung sollte gut entweder in dem Orga Chat oder aber auf Github funktionieren (vlt. findet man sogar noch einen anderen coolen Weg das online zu machen).

**Comment by ROYALBEFF** [comment]
Ich stimme @davidmehren 's Vorschlag komplett zu. Eigentlich können wir die Unterscheidung komplett streichen, da die Gruppen sich selbst organisieren und der Rest öffentlich ist.

**Comment by Lazalatin** [comment]
Wie bereits im Orga Chat von mir angesprochen:

Stimmen sollten nur Personen dürfen, welche:

1. In einer entsprechenden Sitzung anwesend sind, in der zu einer Diskussion eine Entscheidung getroffen werden soll.
2. Der entsprechenden Sitzung hörend beiwohnen (Riot P2P, Mumble, Jitsi, etc.)

Alle anderen Formen der Teilhabe an einer organisatorischen Abstimmung für die AG lehne ich ab. Wer nicht mitbekommt was in einer entsprechenden Sitzung gesagt wird, kann keine fundierte Entscheidung zu dem Thema treffen.

**Comment by davidmehren** [comment]
Ich versuche mal zusammenzufassen:
- Die Rolle des „aktiven Mitglieds“ soll gestrichen werden.
- Bei Orga-Abstimmungen dürfen alle mit abstimmen, die anwesend (egal ob physisch oder digital) sind.
- In den Datenschutz-Chat kommt man, wenn kein bisheriges Mitglied ein Veto einlegt.

**Comment by avahenriette** [comment]
Da habe ich die Frage ob ein Veto einmalig eingesetzt werden soll oder ohne jegliche Anzahl gewidmet wird.

**Comment by ThiefOfTime** [comment]
Es geht nicht darum, dass da eine Person hockt, die sagen kann, finde ich doof machen wir nicht und dann wird es auch nicht gemacht, sondern mehrere Personen, die sagen können /untereinander klären können wie sie die Idee finden und sonst auch ein Schlusswort sprechen können, wenn z.B. Uneinigkeit herrscht.
Es soll einfach nur dazu da sein, dass Abstimmungen nicht manipuliert werden oder aber Leute der AG schaden. Es geht dabei ja nicht nur um die Orga Gruppe sondern um alle Gruppen. Vlt kann man das ja so formulieren:
Pro Gruppe gibt es min. 2 Maintainer. Die Maintainer haben die Aufgabe für Ordnung in der Gruppe zu sorgen und halten, wenn es darauf ankommt, auch den Kopf hin. Die Maintainer sind verpflichtet zu gunsten der AG und der Mitfossler zu entscheiden.
Maintainer haben ein Veto recht, welches sie für jede Entscheidung, die zu treffen ist, einsetzen können. Dieses Veto recht sorgt nur dafür, dass die Thematik erneut untersucht wird. Ein entgültiges Ablehnen der Thematik wäre nur der Fall, wenn die Mehrheit der Gruppenmitglieder dagegen stimmt oder aber alle Maintainer ihr Veto einsetzen.
Maintainer tragen die volle Verantwortung für die Gruppe und das Veto ist nur eine Absicherung für diese einzelne Person.

Das ist erstmal nur eine spontane Idee von mir, bitte korrigieren oder aber eigene Ideen einwerfen. Gruppe bezieht sich dabei nicht auf die AG, sondern auf jeden einzelnen Chat-Raum (verbunden mit der FOSS-AG Untergruppe; Bsp.: Orga, Gemeingüter, Sommerfest, HnS, Raspi an Schulen, Ophase,...)
Ich hoffe ich konnte mich verständlich machen. Ich will damit keine übermächtige Zentralinstanz erzeugen, sondern eine Sicherheit für Abstimmungen (sodass man auf die Rolle des Stimmberechtigten verzichten kann) und die Rolle der Maintainer erneut aufleben lassen. Bzw. Die Rolle des Maintainers auf den Orga Chat übertragen, der nun in der gleichen Kategorie is, wie es die anderen Gruppen sind.


Und jetzt fällt mir auf, dass sich deine Frage, @avahenriette, evtl. auf den Post bzgl der Privaten Gruppe bezog. :D Da wäre der Vorschlag, dass wir das wie bisher behandeln, wir fragen alle Mitglieder des Channels und wenn **keiner** ein Problem mit der Person hat, wird diese dem privaten Channel hinzugefügt. Das würde das Veto bedeuten. Wenn auch nur leichte Bedenken einer Person geäußert werden, wird die Einladung erst mal nicht vergeben. Hieße aber auch, dass das Veto immer eingesetzt werden kann. Ist in der Gruppe tatsächlich sinnvoll, da dort private Dinge besprochen werden, hat ein Mitglied der Privaten-Gruppe ein Problem so ist es erst mal nicht sinnvoll die Person in den Chat einzuladen.

**Comment by avahenriette** [comment]
Alles klar, danke @ThiefOfTime für die Erklärung.

**Comment by davidmehren** [comment]
Abstimmung zum Vorschlag https://github.com/foss-ag/orga_guidelines/issues/40#issuecomment-397871920

Ja: 9, Nein: 0, Enthaltung: 2

**Comment by davidmehren** [comment]
Fixed by #41
