### ISSUE TITLE
Zweiwöchige Orga

### ISSUE THREAD

**Issue by fes0j** [foss-ag/orga_guidelines#42]
Falls wir uns dauerhaft auf einen Wechsel zwischen Orga und Nicht-Orga für die Treffen entscheiden, sollten wir dies hier notieren.

**Comment by dragetd** [comment]
Ich empfinde eine Begrenzung von Orga-Themen ja cool, aber der zweiwöchige Rythmus ist dann doch etwas schade.

Alternativ hätte ich z.B. https://github.com/foss-ag/orga_guidelines/issues/43 vorgeschlagen. :)

**Comment by InnayTool** [comment]
siehe meine Bedenken #43

**Comment by fes0j** [comment]
Ich denke, die Hauptdisskussion findet nun in #43 / #44 usw. statt.

**Comment by fes0j** [comment]
In der heutigen Sitzung gab den Konsens bis auf weiters diesen 2 Wochen-Takt fortzuführen.
