### ISSUE TITLE
Timeboxing von Orga-Themen

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#43]
Pro Thema auf der Themenliste gibt es 10min mit Timer. Verlängerung um weitere 10min nur, wenn alle zustimmen.

Wenn nicht, wird vertagt. RFC!

**Comment by davidmehren** [comment]
Da ich nicht da war, keine Ahnung ob das einem praktischen Problem entstammt. Aber mal meine grundsätzliche Meinung:

Ich finde solche arbiträren Begrenzungen selten hilfreich. Im Zweifel brechen sie eine gesunde Diskussion ab. Der Abbruch einer unfruchtbaren Diskussion ist die Aufgabe der Sitzungsleitung, die ggf. "Stopp, das bringt hier nichts mehr" rufen/vertagen/auf die Mailingliste verschieben kann.
Bei potentiell langwierigen Themen kann sie auch selber ein Zeitlimit festlegen, ohne dass das explizit formalisiert sein muss.

**Comment by InnayTool** [comment]
Ich merke, dass das Konzept was wir momentan verfolgen, bei einigen zu langeweile und Unlust führt.
Ich glaube nicht, dass man das Problem löst, indem man die Disskussionen abbricht nach einer bestimmten Zeit. Ich bin eher für eine Ausdünnung von Orga-Terminen, damit man Platz schafft, um sich für Projekte zu treffen. Einerseits bringt es immer eine Struktur und ein Thema auf der anderen Seite, finden Leute die Themen nicht immer ansprechend. Dazu gehören auch die Stammtischthemen.

**Comment by davidmehren** [comment]
Die harte Lösung wäre, einfach (ggf. mit Termin außerhalb der Reihe) einen nur-Orga-Termin zu schaffen, wo dann Entscheidungen gefällt werden. Wer sich nicht dafür interessiert, bleibt dem einfach fern, muss dann aber auch mit dem Ergebnis leben.

Alternativ: Alles in Issues/nem Discourse/sonstwie online besprechen.

**Comment by InnayTool** [comment]
ja ich halte das für eine Überlgenswerte Idee, aber schon noch mit Orgatreffen und sonst eben Issues.

**Comment by dragetd** [comment]
Timeboxing ist ein verbreitetes Schema zur Verbesserung der Meeting-Kultur. Wenn eine Diskussion interessant ist, wird auch niemand etwas gegen eine Verlängerung haben.

Die Regeln helfen aber dies von einer abritären persönlichen Meinung einer Person (aka 'Moderator', den wir noch nicht mal klar definiert haben) zu lösen.
Diesen unterstellt man dann gerne etwas persönliches, was die Ausübung dieser Position nicht einfacher macht.

**Comment by fes0j** [comment]
Ich gegen eine komplett digitale Orga. Erfahrungsgemäß führen online Disskusionen schneller zu Missverständissen. Durch die Langatmigkeit finde ich das sogar manchmal anstrengender.

Daher nochmal die Idee: behandeln wir die Orga wie eine Kleingruppe. Wenn es für irgendwas eine Entscheidung zu fällen gibt, wird das angekündigt. Danach steht jedem frei, ob er sich am Disskurs beitigen will oder ob andere Dinge interssanter und wichtiger sind (und man den anderen vertraut). Quasi eine dynamische temporäre Komiteebildung, bezogen auf jeweils eine Frage.

**Comment by InnayTool** [comment]
gegen nur online bin ich auch, bei der Kleingruppe sehe ich das Problem, dass es dann zu ungeordnet wird, aber man könnte das probieren.

**Comment by Lazalatin** [comment]
Ich wäre dafür, die Vorschläge von @fes0j und @InnayTool eher in eigene Issues auszulagern. Hier soll nur besprochen werden, was wir von Timeboxing halten.

Ich persönlich kenne das Konzept gut und bin hart dafür.

**Comment by ROYALBEFF** [comment]
Ich würde den Bedenken von @davidmehren da zustimmen. Ich bin mir nicht sicher, wie zielführend Time-Boxing ist. Finde es da besser den 2-Wochen-Rythmus beizubehalten, um somit mehr Zeit für die "spaßigen" Sachen zu haben. (Orga muss nicht zwingend langweilig sein).
Und falls dann immer noch der Bedarf existiert etwas an den Orgatreffen zu ändern, können wir dann ja mal das Timeboxing testen.

**Comment by Eisfunke** [comment]
Ich bevorzuge übrigens auch den 2-Wochen-Rythmus. Nach dem, was @fes0j in #42 schrieb, ist das ja jetzt anscheinend auch allgemein angenommen.

**Comment by dragetd** [comment]
Die Idee mit dem Timeboxing kann eine zusätzliche Idee sein und nicht eine reine Alternative. Ich glaube das ist etwas unter gegangen. Zumindest ein Versuch wäre es wert gewesen finde ich, schade.

Aber ich sehe, dass dies nicht auf so viel Resonanz stößt. Insofern können wir die Idee vorerst einboxen… versteht ihr… Box… okay… xD

**Comment by Lazalatin** [comment]
Ich würde gerne mal demnächst vielleicht mal in Ruhe in einer Orgarunde klären, was Timeboxing bedeutet. Die meisten hier kennen keine Agilität und wissen mit dem Begriff höchstvermutlich nichts anzufangen ;)
