### ISSUE TITLE
Weniger Sitzungen

### ISSUE THREAD

**Issue by InnayTool** [foss-ag/orga_guidelines#44]
Es gibt einige, die sich mehr Zeit in Gruppen wünschen und weniger Orgadiskussion bzw. im ganzen Sitzungen in dem Sinne.

**Comment by davidmehren** [comment]
Bislang war da glaube ich der Plan, dass sich Gruppen einfach selber Termine suchen. Was spricht dagegen?

**Comment by InnayTool** [comment]
nichts, aber es wird häufig angeführt, dass man keine Zeit hat für Sitzung und Gruppentreffen.

**Comment by dragetd** [comment]
Ich sehe auch Alternativen: Im Chat treffen/diskutieren? Mumble Meetings? Mailingliste?

**Comment by InnayTool** [comment]
Wozu und wofür siehst du alternativen?

**Comment by Lazalatin** [comment]
Ich glaube, dragetd bezieht sich hierbei darauf, dass dies auch Kanäle für Gruppentreffen sind.

Anyway, ich bin der Ansicht, dass wir mehr zur Selbstorganisation streben sollten (Siehe auch das Timeboxing issue) und dafür wäre es gut, eher eine "work remotely, report centrally"-Strategie zu verfolgen und Sitzungen von Gruppenarbeit zu entkoppeln.

**Comment by dragetd** [comment]
Okay, und was ist jetzt das Ziel dieses Issues bzw. soll als Ergebnis raus kommen?

**Comment by InnayTool** [comment]
Das Ziel war darüber zu reden, ob man die Zahl der Sitzungen reduziert, sich aber trotzdem noch trifft, aber in einem anderen Rahmen.

**Comment by fes0j** [comment]
@InnayTool Den Wunsch kannte ich noch nicht. Ich habe bisher nur verstanden, die bisherigen Treffen so zu öffnen, dass sie einzelnen Projekten mehr Raum bieten.

**Comment by InnayTool** [comment]
Das funktioniert aber meiner Meinung nach eher so mäßig

**Comment by dragetd** [comment]
> Das Ziel war darüber zu reden, ob man die Zahl der Sitzungen reduziert, sich aber trotzdem noch trifft, aber in einem anderen Rahmen.

Also, dass die Untergruppen sich öfter treffen ist erwünscht und es wäre cool, wenn man mehr davon hören würde (z.B. in den Kalender schreiben ;-) )
Das liegt aber an den Leuten… das muss von denen aus kommen.

Sprich, was für dieses Issue bleibt: Du willst seltener ein Plenums-Treffen haben? Seltener als wöchentlich im Moment? Wenn ja, dann passe bitte den Titel des Issues an, danke.

Was das angeht, finde ich aber das wöchentliche Treffen für sehr wichtig, weil man sich daran ein wenig orientieren kann. Ich würde das ungern seltener machen.

**Comment by InnayTool** [comment]
Es geht darum, ob man immer eine Sitzung macht in der Form, wie wir es gerade tun.
Ich treffe mich auch sehr gerne jede Woche, aber es muss ja nicht immer die gleiche Struktur sein.

**Comment by ROYALBEFF** [comment]
Da muss ich @InnayTool  recht geben. Ich finde die Idee eigentlich ganz gut nur alle zwei Wochen ein Orgatreffen zu machen. Was haltet ihr von dem Vorschlag jedes nicht Orgatreffen als ein freies Treffen zu gestalten? Sprich, weder Stammtisch noch sonst was, sondern nur Treffen, um sich auszutauschen bzw in Kleingruppen zu arbeiten. Die Stammtischthemen sind zwar ganz cool, aber wenn alles in einem Raum stattfinden soll, laeuft es ja idR so, dass bei einem Stammtischthema es nur sehr schwer moeglich ist in einer Kleingruppe zu arbeiten.

**Comment by Lazalatin** [comment]
Ich möchte gerne widersprechen. Ich bin sehr wohl der Ansicht, dass eine gewisse Struktur erhalten bleiben muss. Ich spüre hier eine anarchistische Tendenz, die mir nicht so gut gefällt. Für Chaos sind in Dortmund andere Gruppen zuständig.
Ich finde das bisherige Format gut und es auch legitim dass man zweiwöchig Orga und wöchentlich Stammtisch+Kleingruppen macht.

Aktuell scheint der Overhead bei Orgathemen auch eher gering zu sein, wegen der vielen Issues auch hier im Repo. Und zudem sollte jeder, der für den Stammtisch ein Thema mitbringt auch das Gehör aller FOSSler haben können, die gerade im Raum sind. Auch hier belief sich so etwas in letzter Zeit auf nicht mehr als eine halbe Stunde. Ich sehe also daher aktuell überhaupt keinen Änderungsbedarf und finde dafür sollten weiterhin interessante Themen in den Stammtisch. 

Technischer Schickschnack, vorgestellte Projekte, Dinge an denen jeder von uns lernen möchte. Und wenn das mal in einer Woche nicht vorhanden ist: Machen wir halt ganz ohne Struktur jeder sein Ding (oder Gruppen ihr Ding, je nachdem :grin: )

**Comment by Lazalatin** [comment]
Ich sehe hier keine weiteren Beschwerden bzgl der aktuellen Struktur. Ich schließe damit dieses Issue :)
