### ISSUE TITLE
Nextcloud zur Fachschaft migrieren

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#45]
Wir haben überlegt, die NC aufzulösen und stattdessen die NC der Fachschaft zu nutzen.
Dafür spricht, dass wir leine Dopplung der Infra habe und diese nicht selbst Maintainen müssen.

Ich sehe allerdings auch Probleme: Die Admins müssten uns explizit cloud.foss-ag.de mit in die NC-Domains Eintragen. Wenn nicht, dann hätten wir nur HTTP-Weiterleitungen - wenn man selbst Resourcen Teilt, hätten die dann den 'falschen' Link.

Dazu kommt, dass Fachschafts-Accounts notwendig sind. Wir haben aktuell beide Admins in der FOSS-AG und die sind auch super toll, aber wir sind trotzdem abhängig von Ihnen die Accounts anzulegen. Und bekommt dann wirklich jeder der möchte einen Account? So sehen unsere Guidelines das aktuell vor.

Ich bin super froh, dass die Fachschaft existiert und David als Admin rockt… aber generell empfinde ich es als besser ein wenig Unabhängigkeit zu bewahren. Die Uni als solche hat uns bis jetzt wenig unterstützt. Mir wäre es lieber, wenn wir unabhängiger bleiben (was vor allem die öffentlichen Dinge angeht).

Wäre gegen eine Migration.

**Comment by InnayTool** [comment]
Ich betrachte es immernoch als unnötigen Overhead.

 Auf welchen Link man jetzt verweist finde ich auch eher unwichtig. Das mit den Fachschaftsaccounts ist meiner Meinung nach auch nich das große Problem, da unsere Mitglieder alle einen Account bekommen haben und ich auch nicht sehe, wer ihn nicht bekommen würde und wenn es zu dem Fall kommen sollte, kann man auch noch eine andere Lösung finden.

Ich bin der Meinung wir sind eh nicht unabhängig und eine AG der Fachschaft, sollte man das ändern wollen is das natürlich anders, aber sollte man die Strukturen nutzen.

**Comment by dragetd** [comment]
Links die man im Internet verteilt zu freigegeben Resourcen. Die bleiben auch im Netz und sollten dauerhaft unter cloud.foss-ag.de/… bleiben, imho.

Und unsere Aktionen sind schon seit längerem nicht mehr sehr Uni-Zentriert. Wir sind eine FSInfo-AG, ja, nur schließen wir ja auch nicht-TU-ler nicht aus.

**Comment by davidmehren** [comment]
Mal grundsätzlich: Die FSI-Admins fänden es schön™, wenn Dienste nicht unnötig gedoppelt sind, weil weniger Angriffsfläche & Ressourcenverbrauch.

Zu den anderen Punkten:
- Accounts für neue Leute waren nie ein Problem und es ist auch nicht geplant da was an der Policy zu ändern. Vielleicht gibts auch irgendwann ein Self-Signup.
- Links: Ja, die gehen kaputt. Ich habe allerdings nur [eine Freigabe](https://cloud.foss-ag.de/index.php/s/ZcH44yNA3DEXkBp?path=%2FHack%20and%20Snack%2FStatistical%20Computing) der Cloud im Netz verklinkt gefunden. Das kann man entweder an Ort und Stelle (hier Meetup) ändern oder einfach auf die neue Stelle manuell weiterleiten. Haben wir an noch anderen (nicht von uns bearbeitbaren) Stellen auf die FOSS-AG Cloud verlinkt?

> Und unsere Aktionen sind schon seit längerem nicht mehr sehr Uni-Zentriert. Wir sind eine FSInfo-AG, ja, nur schließen wir ja auch nicht-TU-ler nicht aus.

Sehe da kein Gegenargument drin, *.fachschaften.org ist ja explizit auch für nicht-TUler.

**Comment by Lazalatin** [comment]
Ich zitiere mal eben frei aus meiner Nachricht bei den FsI Admins:

> Ich verstehe dass man die Dienste vereinigen will. Aber insbesondere die Nextcloud und noch einige andere Services leben von Dezentralisierung. Was spräche dagegen, solange es nicht Ressourcenintensiv wird, diese Dezentralisierung auch zu leben. Klar, wenn jetzt jede AG plötzlich ne eigene Cloud will wirds dämlich, aber ich denke dass dies durchaus unterstützenswert wäre.
Alternativ wird seitens uns Admins auch darüber nachgedacht wieder auf eine fremdgehostete VM zu migrieren. Aber ehrlich gesagt fühle ich mich bei dem Gedanken dass die FsIAdmins der Host sind, sehr viel wohler.

Wie dort auch bereits festgestellt wurde: Angriffsfläche ist irrelevant, da die FOSS-AG Cloud in einer VM hängt. Ressourcenverbrauch ist _aktuell_™ kein Problem, aber das kann sich ändern.

Bevor die Cloud einfach so™ migriert wird, würde ich aber erst einmal in Ruhe prüfen wollen, was da alles an datenschutzrelevanten Dingen liegen und da Einzelentscheidungen fällen wollen.

**Comment by davidmehren** [comment]
> was da alles an datenschutzrelevanten Dingen liegen und da Einzelentscheidungen fällen wollen.

Inwiefern datenschutzrelevant?
Zu schützen vor den FSI-Admins?
Würde beim aktuellen Betriebsort der VM nicht so viel Sinn ergeben.

Zu schützen vor anderen Nutzern?
Das betrifft (soweit mir bekannt) ja vor allem (nur?) Finanzdokumente, die nicht alle Mitglieder der FOSS-AG-LDAP-Gruppe was angehen. Kann man das nicht mittels persönlicher Freigaben außerhalb des FOSS-AG-Gruppenordners lösen?

**Comment by dragetd** [comment]
Was mir auch noch einfällt: Federaten mit anderen NCs geht auch nur nach Admin-Freigabe, oder?

**Comment by Lazalatin** [comment]
> > was da alles an datenschutzrelevanten Dingen liegen und da Einzelentscheidungen fällen wollen.
> 
> Inwiefern datenschutzrelevant?
> Zu schützen vor den FSI-Admins?
> Würde beim aktuellen Betriebsort der VM nicht so viel Sinn ergeben.
> 
> Zu schützen vor anderen Nutzern?
> Das betrifft (soweit mir bekannt) ja vor allem (nur?) Finanzdokumente, die nicht alle Mitglieder der FOSS-AG-LDAP-Gruppe was angehen. Kann man das nicht mittels persönlicher Freigaben außerhalb des FOSS-AG-Gruppenordners lösen?

Ich meinte das eher im Allgemeinen. Wir müssten halt einmal durchgehen was da an Daten ist und jeden Fragen, der da Dinge drin hat. Halte ich für das konfliktfreieste Vorgehen.

**Comment by Lazalatin** [comment]
> Was mir auch noch einfällt: Federaten mit anderen NCs geht auch nur nach Admin-Freigabe, oder?

Das ist richtig, aber wo ist da konkret die Problematik bei einem Umzug auf die FsI-NC?

**Comment by davidmehren** [comment]
> Was mir auch noch einfällt: Federaten mit anderen NCs geht auch nur nach Admin-Freigabe, oder?

Also Federation ist an, "Ermögliche Nutzern dieses Servers Freigaben an Gruppen auf anderen Servern zu senden" bzw "zu empfangen" allerdings nicht. Nutzer können also auf jeden Fall beliebig freigeben, wenn das wer für Gruppen braucht kann man das ggf. auch noch einschalten.

**Comment by Eisfunke** [comment]
Ich fände mittlerweile beides okay.

NC ist für Federation ausgelegt, es wäre okay, wenn wir was eigenes behalten, da das ja nun aber sowieso auf dem selben Server läuft, können wir auch umziehen. (Beim Git z.B. ist es etwas anderes, weil das kein Federation kann, da halte ich möglichst wenigst Zersplitterung für wichtiger) Datenschutzrelevante Dinge werden halt wie momentan an sich auch über private Sachen geregelt. Macht auch am meisten Sinn, finde ich.

Sorgen wegen zukünftigen Admins o.ä. habe ich an sich nicht. Fachschaftenaccounts waren schon immer frei zu haben, sehe kein Anzeichen, dass sich das ändern sollte, und ein unkooperativer zukünftiger Admin könnte bei der aktuellen Cloud-auf-FSI-Server-Situation auch Probleme bereiten. Im unwahrscheinlichen Notfall wechseln wir halt irgendwann wieder auf was anderes.

TL;DR: Mir gleich, würde aber empfehlen, den Umzug jetzt durchziehen :clown_face:

**Comment by dragetd** [comment]
@Eisfunke Und der Aspekt mit den Links cloud.foss-ag.de die dann nicht mehr möglich sind?

Wollte nur sicher gehen, dass du das auch berücksichtigt hast. :)

**Comment by dragetd** [comment]
Zwei dafür, zwei dagegen. Ich lass das Issue hier einfach mal rumlungern bis das Thema wieder aufkommt…

**Comment by fes0j** [comment]
Mein Zwischenvorschlag: den Kalender, in dem unsere Treffen eingetragen sind, können wir zur Fachschaft migrieren. Die Daten, die privat sind, können wir dann weiter selbst verwalten.

**Comment by InnayTool** [comment]
Das mit dem Kalendar finde ich auf jeden Fall sehr sinnvoll, da wir dann keine Accounts anlegen müssen, damit Leute den bearbeiten können.

**Comment by dragetd** [comment]
Warten wir noch einmal bis übernächste Woche (noch ein Orga-Treffen dazwischen). Wenn es keine Einwände gegen die Migration vom Kalender gibt, dann machen wird das.

Auch von meiner Seite aus OK!

**Comment by davidmehren** [comment]
Ich verstehe nicht, warum wir das jetzt ewig schieben, nur weil hier niemand mehr antwortet. Wir könnten einfach mal über die Migration grundsätzlich abstimmen?

**Comment by Lazalatin** [comment]
Ich sehe da keinen Sinn.
Wenn es keine Diskussion gibt, dann gibt es kein von ausreichend zahlreichen Personen wahrgenommenes Problem mit dem Status Quo.
Wenn das so ist, brauchen wir den Aufwand auch einfach erst gar nicht betreiben.
Ich persönlich hätte das Issue ja schon geschlossen. ¯\_ (ツ) _/¯ 

Am 4. März 2019 10:28:43 MEZ schrieb David Mehren <notifications@github.com>:

**Comment by dragetd** [comment]
Stimmt… *dieses* Issue ist eigentlich erledigt. Es geht um die Migration des Kalenders… dazu mache ich mal ein neues Issue auf.

#47

**Comment by dragetd** [comment]
Letzte Sitzung wurde gewünscht, dass wir diese Entscheidung noch einmal abstimmen.
Ich würde das gerne hier in diesen Issue machen und bis zum 18.03 laufen lassen.

Frage: Soll die *komplette* NC zu cloud.fachschaften.org migirert werden?

Daumen hoch: Ja
Daumen runter: Nein
JEDES andere Icon: Enthaltung

**Comment by Lazalatin** [comment]
Also, ich fasse zusammen:
Es wird ein Thema eröffnet, dass augenscheinlich nicht im Interesse der breiten Masse liegt, da die Diskussionsbereitschaft sich auf eine Gruppe beschränkt. Daraufhin wird das Thema, welches außer Overhead *nichts* zu bieten hat, richtigerweise geschlossen.

Nun behandeln wir mit der Neueröffnung des Themas den Wunsch von zwei(!) Mitgliedern, statt uns mit produktiveren Fragen wie zB #47 zu beschäftigen und machen sogar eine *Abstimmung* auf Grund eines mangelhaft behandelten Themas?

Für mich ist das ganz großer Kindergarten. Entschuldigt die Ausdrucksweise.
Ich beantrage in der kommenden Sitzung die erneute Schließung des Themas.

**Comment by davidmehren** [comment]
Um auch mal einen genervten Kommentar zu schreiben:
Die FOSS-AG verstößt mit der Cloud aktuell gegen die [Nutzungsbedingungen der FSI](https://fsinfo.cs.tu-dortmund.de/fsr/edv#nutzungsbedingungen_fuer_server_der_fsi), im Spezifischen `Dopplungen mit bereits auf der Infrastruktur der FsI betriebenen Diensten sind zu vermeiden.`. Mal davon abgesehen, dass die FSI-Admins nicht vor haben, deshalb irgendwas zu tun, sollte das schon zu einer Diskussion & Abstimmung in der ganzen AG führen, ob man den Verstoß nun fortsetzen möchte oder nicht.

**Comment by dragetd** [comment]
So viel zum Thema 'wir stehen ja immer mit den Admins gut' und 'sind weiterhin unabhängig' was auch mal Argument in einer Diskussion war.

Ist das jetzt ein ernsthaftes Bedenken deinerseits @davidmehren und etwas was dich stört?

**Comment by Lazalatin** [comment]
Ich war ja dabei als das geschrieben wurde und nach meiner Erinnerung war das keine "hard line" nach dem Motto: Wer gleiche Services betreibt, der fliegt.

Viel eher sollte das einfach dazu ermutigen sich nicht erst die Mühe zu machen, wenn es die FsI schon hat und halt zweimal darüber nachzudenken (und mit den Admins zu reden) bevor man das (weiter-)betreibt.

Keinesfalls würde ich hier das Wort "Verstoß" verwenden. Das erscheint mir tendenziös.

Sollte das im Sinne der aktuellen Admins gegenteilig als "hard line" empfunden werden, müssen wir dazu mal ein Admin-to-Admin Gespräch führen bevor wir die AG damit belästigen, denn die meisten Member haben keine Ahnung worum es hier eigentlich geht.

Am 13. März 2019 11:41:22 MEZ schrieb David Mehren <notifications@github.com>:

**Comment by davidmehren** [comment]
Also um das klarzumachen: Die Nutzungsbedingungen werden hier (und auch bei jedem anderen nicht offensichtlich hirnrissigem Dienst) nicht als Begründung genutzt werden, irgendwas abzuschalten. Ich dachte da sei ich mit meinem Nebensatz schon ausreichend deutlich gewesen. Also FSI-Admin habe ich, wenn die FOSS-AG gute Gründe gegen eine Migration liefert, kein Problem. Liefert sie keine, habe ich ein Problem, das führt aber nur zu persönlichem Unglücklichsein und nichts weiter. Punkt.

Ich hätte mir nach dem Aufkommen des Themas eine Diskussion um "gibt es praktische Gründe, die gegen eine Migration sprechen" gewünscht. Stattdesssen wird nun ganz viel metadiskutiert und das Thema soll weil es "nicht im Interesse der breiten Masse" liegt geschlossen werden. Ich hätte gedacht, zumindest der Versuch der Einhaltung von nicht aus Spaß aufgestellten Nutzungsbedingungen liegt eigentlich im Interesse aller Beteiligten?

Um mal zu den Sachargumenten zurückzukommen: Ich hatte [hier](https://github.com/foss-ag/orga_guidelines/issues/45#issuecomment-455856909) schonmal nach Links zu FOSS-Cloud geschaut, die man ändern/manuell weiterleiten müsste. Hat da noch wer Ergänzungen zu, denn die aktuelle Anzahl (ein Link) scheint durchaus machbar.

**Comment by dragetd** [comment]
Was Links angeht: Mir geht es nicht nur um Links die du gefunden hast, sondern generell um alle Links, die dann auch nicht mehr unsere Domain nutzen und die Außendarstellung der AG auch weiter zerhacken.

Und - du sprichst das Argument ja selber an - es gibt anscheinend mehrere sachliche, konkrete Gründe, für beide Seiten.


Was mich hier einfach Aufregt und traurig macht:
Hier sind zwei gleich große Partien, die jeweils eine 'starke Meinung' haben, aber scheinbar hat niemand Argumente die Meinung des anderen zu ändern. Und mir ist schon klar, dass der Default 'nichts tun' dann zu 'meinem Gunsten' ausfällt, aber wenn du behauptest 'du musst mir 10€ geben' und ich sage 'Nein, muss ich nicht' ist der sinnvolle Default auch nicht, dass ich dir trotzdem 10€ geben.
Ich habe mir im Vorfeld Mühe gegeben und in Sitzung**en** und Naricht**en** Leute zur Beteiligung aufgerufen, um da einen sachlichen Diskurs zu haben. Stattdessen scheint das zu etwas persönlichem zu eskalieren, **was ich total scheiße finde!**
Das tut uns als AG überhaupt nicht gut, da jetzt so viel Energie rein zu stecken und das auf ein persönliches Level zu ziehen.

Ob es nur eine Anmerkung war oder nicht, die Aussage mit 'FSI Regeln' ist einfach eine Art Eskalation der Diskussion die ich für VÖLLIG daneben halte und ich mir im ersten Moment dachte: 'Okay, ist valide, dass es diese Regeln und Bedenken gibt, diese aber hier aufzubringen ist ein Argument dafür, dass wir wieder einen eigenen Server brauchen um unabhängiger zu sein'. Zahle ich auch selbst und wollte ich schon fast im vorherigen Post schreiben, habe es mir aber auch verkniffen weil das ähnlich eskaliert.

Mir ist wichtig, dass jeder der aktiv Dinge in der AG voran treibt, auch Gehör bekommt und Spaß hat sich bei allem zu beteiligen.

Wir sind bis jetzt noch ein sehr harmonierender Haufen der echt tolle Veränderung schafft. Und es gibt so viel dämlichere Themen bei denen wir uns intern den Kopp einschlagen können statt diesem!
Mir ist der Zusammenhalt und die Motivation der Leute viel wichtiger. Ich hoffe dass wir (Yannik, David, Chris und ich) uns mal bei einem Kaffee zusammensetzen können und über die 'Texte zwischen den Zeilen' reden können.

In Zukunft wünsche ich mir aber, dass wir solche Themen anders angehen!

Zur NC: Einen letzten technischen Vorschlag hätte ich. Es gibt die Einstellung 'trusted_domains', eine Möglichkeit die Fachschafts-Cloud unter ebenfalls 'cloud.foss-ag.de' verfügbar zu haben. Dies wäre etwas, was zumindest eins meiner stärksten Bedenken abschwächt (u.a. die Diffusion der AG). Eine zukünftige Migration zu einer mehr dezentralisierten, eigenen Instanz wäre auch mit etwas Datanbank-Magie möglich wo wir die Share-Tokens rauspopeln damit sie weiter gültig bleiben.

Wäre dies eine Möglichkeit, @davidmehren ? Und falls es nicht möglich ist, so wäre ich trotzdem mit einer Migration zur Fachschaft einverstanden, unter der Voraussetzung, dass wir uns mal zusammensetzen, um uns mal auszuquatschen (nicht über die Entscheidung selbst, sondern darüber wie die Diskussion geführt wurde)

Und wie sieht es mit @Lazalatin und @ThiefOfTime  aus, könntet ihr damit leben? Auch wenn mein Vote sich damit von 'pro' zu 'neutral' ändert und wir dann eine Mehrheit hätten, mir ist auch wichtig, dass ihr damit leben könnt.

**Comment by davidmehren** [comment]
> sondern generell um alle Links, die dann auch nicht mehr unsere Domain nutzen und die Außendarstellung der AG auch weiter zerhacken.

Sehe ich so nicht (wir nutzen ja auch das CodiMD von fachschaften.org und den Matrix-Server da, ohne das es jemanden stört), aber diese ganze Fachschaftsverbundenheitssache sollte man besser an anderer Stelle diskutieren.

> Aussage mit 'FSI Regeln' ist einfach eine Art Eskalation der Diskussion

Ich hatte diese Diskussion iirc mit Verweis auf eben diese Regeln gestartet. Mir ist der Conflict of Interest an der Stelle durchaus bewusst, daher auch der erste Absatz im vorherigen Kommentar. Ich finde es schade, dass das Einhalten der Regeln in der bisherigen Diskussion keine Rolle spielte und jetzt als Affront angesehen wird.

> eine Möglichkeit die Fachschafts-Cloud unter ebenfalls 'cloud.foss-ag.de' verfügbar zu haben

Kriegen wir hin.

> dass wir uns mal zusammensetzen, um uns mal auszuquatschen 

Gerne, aber erst im April :D

**Comment by Lazalatin** [comment]
Ich schließe mich @davidmehren an, dass wir das gerne im April mal so besprechen sollten. Daher werde ich in der heutigen Sitzung auch nichts weiter dazu verlieren.
Des Weiteren habe ich immer noch Bauchschmerzen damit, die Marke "FOSS-AG" (ja ich weiß, ist keine eingetragene Marke, aber wir bauen uns aktuell einen Ruf auf) mit der Fachschaft zu verschmelzen, die in meinen Augen uns bisher mehr bürokratische Steine in den Weg legte (@davidmehren wird sich erinnern) als uns bei unserer Arbeit zu helfen. Ich habe die Vision einer studentischen Arbeitsgemeinschaft, welche über ihre fachschaftlich-universitären Grenzen hinweg Einfluss nehmen kann und aktiv ist (haben wir schon viele Male getan). Wir wollen die Verbreitung des Wissens und der Verwendung von F(L)OSS voranbringen. Und damit auch dediziert als Ansprechpartner auftreten, neben der Fachschaft.

Nichtsdestotrotz denke ich auch, dass @dragetd einen vernünftigen Vorschlag macht und möchte mich daher mit den oben gegebenen Bedenken zurücknehmen. Ich möchte gerne im April dafür einen festen Termin dazu haben, wo wir das ganze planen und dann technisch umsetzen. Hat da jemand einen konstruktiven Vorschlag zur Findung? :grin:

**Comment by Lazalatin** [comment]
Ich würde gerne das mal konkret besprechen und glaube dass wir im Grunde nur mal die Modi besprechen sollten, unter denen etwas auf der Fachschaftscloud liegt.

Ich setze das mal auf nach unserem Geburtstag. Ich setze das passenderweise auf die TOP-Liste :+1:

**Comment by dragetd** [comment]
Done
