### ISSUE TITLE
Vorschlag: Kalender, in dem unsere Treffen eingetragen sind, zur Fachschaft migrieren

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#47]
Mein Zwischenvorschlag: den Kalender, in dem unsere Treffen eingetragen sind, können wir zur Fachschaft migrieren. Die Daten, die privat sind, können wir dann weiter selbst verwalten.

_Originally posted by @fes0j in https://github.com/foss-ag/orga_guidelines/issues/45#issuecomment-464835381_

**Comment by dragetd** [comment]
Das mit dem Kalendar finde ich auf jeden Fall sehr sinnvoll, da wir dann keine Accounts anlegen müssen, damit Leute den bearbeiten können.

_Originally posted by @InnayTool in https://github.com/foss-ag/orga_guidelines/issues/45#issuecomment-465564684_

**Comment by dragetd** [comment]
Warten wir noch einmal bis übernächste Woche (noch ein Orga-Treffen dazwischen). Wenn es keine Einwände gegen die Migration vom Kalender gibt, dann machen wird das.

Auch von meiner Seite aus OK!

**Comment by Lazalatin** [comment]
Make it so! Die zwei Wochen sind rum ;)

**Comment by dragetd** [comment]
Done
