### ISSUE TITLE
Issues erst schließen, wenn es eine Mehrheit gibt oder es umgesetzt wurde

### ISSUE THREAD

**Issue by InnayTool** [foss-ag/orga_guidelines#48]
Ich rege hiermit an einen Issue erst zu schließen, wenn wir einen Beschluss gefasst haben.
Sollte es einen Gleichstand geben wie in Issue #45 gesehen, sollte er meiner Meinung nach offen bleiben, da das Problem offensichtlich nicht gelößt wurde.
Also Issues sollten geschlossen werden, wenn sie obsolet sind.
Dazu gehört es, wenn eine Entscheidung gefällt wurde (durch eine Mehrheit) oder die Maßnahme umgesetzt wurde.
Falls dann neue Zweifel aufkommen, kann ja trotzdem weiterdiskutiert werden. Dies sollte natürlich nur mit neuen Argumenten geschehen und nicht um die eigene Meinung durchzudrücken.

**Comment by dragetd** [comment]
Also eine Diskussion sinnloser Weise weiter führen nur um alle Beteiligen so lange zu nerven bis niemand mehr Lust hat?

Speziell mit Hinblick auf #45 halte ich diesen Vorschlag gerade nicht für konstruktiv.

Man muss auch mal Verantwortungen übernehmen und Entscheidungen treffen. Wir haben z.B. das leider wenig beachtete Maintainer-Prinzip welches auch Verantwortungen abbildet. Z.B. vertraue ich den Grafikern und lasse sie auch in gewissen Rahmen einfach mal machen. #45 war z.B. eine Admin-Angelegenheit, und auch da hätte ich mir ein wenig Vertrauen gewünscht.

:-(

**Comment by InnayTool** [comment]
Nein ich meine nicht, dass man weiter diskutieren sollte, wenn man nichts zu sagen hat, aber man hat auch nichts davon den Issue zu schließen. Wenn man dann neue Argumente oder mehr Leute hat, die das betrift/berührt/sonstig was angeht, können dann noch was dazu sagen.

**Comment by Lazalatin** [comment]
Ich halte dagegen: Wenn ein Thema nicht weiter diskutiert wird und die "Verantwortlichen" welche Ansprechpartner für das Thema sind (wie Michael und ich bei #45) keinen konkreten Handlungsbedarf aus der bisherigen Diskussion ableiten, dann ist es es durchaus legitim das Issue zu schließen.
Wenn es (wieder) vermehrt Interesse gibt, oder weitere Kommentare gegeben werden welche das tatsächliche *Bearbeiten* des Themas durch $VerantwortlichePersonen notwendig machen, *dann* kann und sollte man das Issue wieder öffnen. Insofern ist ein geschlossenes Issue für mich ein Indikator dafür, dass das Thema aktuell nicht "bearbeitet" wird.

**Comment by Lazalatin** [comment]
@InnayTool hältst du dieses Thema noch für aktuell?

**Comment by dragetd** [comment]
@InnayTool Dein Wunsch in allen Ehren, aber jetzt liegt hier eine Issue-Leiche. Und nun? :D

**Comment by InnayTool** [comment]
Ich würde das nicht als Leiche bezeichen. Ich finde dieser Issue dokumentiert die Uneinigkeit und unsere unterschiedliche Auffassung wie diese Issues verwendet werden sollten. Ich sehe den großen Vorteil bei zwei offenen Issues nicht; hier maximale "Ordnung" zu schaffen. Aber wenn ihr ihn zu machen wollt, macht ihn zu. Wäre nicht so, dass es in diesem Repo so unglaublich viel Aktivität gäbe, dass das eine relevante Auswirkung hätte. ^^

**Comment by dragetd** [comment]
Naja, dan stelle einen PR und versuche das zu dokumentieren.

Es ist nur schwer, wenn wir keine offizielle Gruppe sind, eine 'Mehrheit' fest zu stellen. Ich wüsste nicht wie sich das umsetzen lässt. Besser fänd ich z.B.: "Ein Issue kann nach einem Monat ohne Aktivität geschlossen werden. Wer das vermeiden will, soll im Issue ankündigen, dass es in der Sitzung besprochen wird um dann da einen Entschluss zu finden."
Das ist realistischer umsetzbar.

Das Issue jetzt hier offen lassen 'einfach weil', ist doof, Innay.

**Comment by Lazalatin** [comment]
Wir entschlossen in der Sitzung, dass dieses Meta-Issue zur Zeit nicht zielführend ist und haben es daher geschlossen. (Frei nach der Regel: Es tut uns nicht (mehr) weh, verschwenden wir keine Zeit darauf 😉 )
