### ISSUE TITLE
FOSS-AG Dortmund Matrix Raum auf neuen E2E Raum migrieren.

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#50]
Vorsclag:
Der #foss_ag:matrix.org/fachschaften (FOSS-AG Dortmund) Raum bekommt einen neuen Namen/Alias mit einem '_legacy' Suffix. Er bleibt vorerst bestehen. Wir erstellen einen neuen Raum mit dem alten Namen/Alias. Die selben Leute bekommen die selben Rechte. Dafür wird der Raum aber E2E Crypto aktiviert. Der alte Raum bekommt eine Info, wird aber noch min. 3-6 Monate weiter betrieben, bevor er den Tombstone bekommt.

Hintergrund: Ich bin davon überzeugt, dass die Usability von Matrix mit E2E sehr schlecht war, als das wir das hätten früher machen können. Es war richtig, das noch nicht genutzt zu haben.

Aber ich habe auch das Prinzip 'Encrypt everything'. Und Element ist weit gekommen. Ich wäre es bereit, es auszuprobieren. Wir würden auch viele der 'Leichen' in unserem Raum los werden.

**Comment by dragetd** [comment]
Wir haben im Chat entschieden, dass es noch Probleme gibt.

- Alte History kann von Leuten die neu verbinden, nicht gelesen werden. https://github.com/vector-im/element-meta/issues/647
- Räume sind nicht durchsuchbar. https://github.com/vector-im/element-android/issues/47

Aktueler Stand: Wir ziehen NICHT um!

**Comment by InnayTool** [comment]
Wir haben jetzt alle umgezogen oder?

**Comment by dragetd** [comment]
Umgezogen, ja. Aber der Raum ist noch nicht E2E encrypted.

Wobei ich fast dafür wäre, das bald mal zu machen. Ich frage mal rum.

**Comment by dragetd** [comment]
E2E ist erst ab Raum-Modus 'Invite' möglich und beide unsere Räume sind öffentlich. Insofern geht das gar nicht. Schade, aber ok.

**Comment by davidmehren** [comment]
Das ist falsch, E2EE kann man immer machen.
Bei eh öffentlichen Räumen macht Verschlüsselung aber einfach keinen Sinn.
