### ISSUE TITLE
FOSS-AG Dortmund Matrix Raum auf neuen v6 Raum migrieren.

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#51]
Hier sollen alle offene Punkte gesammelt werden die wir geklärt/gelöst haben wollen, um den Raum auf Matrix Raum v6 zu migrieren.

Ebenfalls wollen wir hier Erfahrungen sammeln.

Ein Upgrade funktioniert mittels eine Tombstones mit einem Link zur neuen Raumversion.

**Comment by davidmehren** [comment]
Der einzige Nachteil, der mir einfällt ist UX: alle Leute müssen einmal manuell auf "ich will in den neuen Raum" klicken.

**Comment by dragetd** [comment]
Bei einem Test mit dem Orga-Chat:
FluffyChat hat den alten Raum nicht ausgeblendet und den neuen ebenfalls angezeigt. Änderungen am alten Raum waren plötzlich Änderungen im neuen Raum. Das war aber vor 3-4 Monaten, FluffyChat hatte evtl. updates.

Alternativ können wir auch einfach 'nur' einen neuen Raum erstellen und den alten langsam deprecaten.


@davidmehren Ich sehe das auch als Vorteil… wir haben VIELE(!) Leichen in der Member-Liste.

**Comment by davidmehren** [comment]
> FluffyChat hat den alten Raum nicht ausgeblendet und den neuen ebenfalls angezeigt.

Ja, das ist die Schuld von FluffyChat, das blendet Räume mit Tombstone nicht aus. 

> Änderungen am alten Raum waren plötzlich Änderungen im neuen Raum.

Das äh klingt nach Bedienungsfehler? :D

**Comment by fes0j** [comment]
Risiken machen das Leben bunter und spannender...

**Comment by dragetd** [comment]
Jo, deswegen haben wir es einfach getan! :-D
