### ISSUE TITLE
Auch jeder nicht-Member kann ein vollwertiger Contributer sein

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#8]
Wir machen uns teilweise Sorgen, dass Leute nicht vernünftig daran arbeiten können weil PRs nutzen müssen. Das stimmt aber nicht. Jeder kann vom Repo-Admin zu einem vollwertigen Contributer gemacht werden, selbst externe. Dann kann man ganz normal mergen.

Evtl. könnte man das irgendwie auch mit in den Text packen. :-)

**Comment by Lazalatin** [comment]
Da es sich hierbei um Mechanismen handelt die wir nicht definieren müssen, sondern GitHub zu eigen sind, halte ich dies für überflüssig.
Ich verstehe auch den ganzen Trubel um PRs nicht. Wir haben in Sitzung Nr.62 gezeigt, dass dies ein sinnvoller Workflow ist.
But back to topic: Ich plädiere dafür das Issue als `wontfix` abzulehnen.

**Comment by dragetd** [comment]
Alles klar!
