### ISSUE TITLE
Format der Lizenz - so viel Freizeilen nötig?

### ISSUE THREAD

**Issue by dragetd** [foss-ag/orga_guidelines#9]
In der LICENSE sind sehr viele Freizeilen, selbst zwischen Aufzählungspunkten. Muss das so? :-P

**Comment by Lazalatin** [comment]
Also wenn du mich fragst: Es wird so ausgeliefert, lass es gut sein und forget it :D
Aber das ist nur meine Meinung :+1:

**Comment by dragetd** [comment]
Wenn das das Originalformat ist, okay xD
